# Zero-Shot Classification (Llama-3.2-11B-Vision-Instruct)

Run zero-shot classification across **both tasks** and **all 3 modalities** (train + test splits).

**12 experiments total** (2 tasks × 3 modalities × 2 splits), run sequentially with cleanup between each.

## Setup

In [ ]:
import sys, os, gc
sys.path.insert(0, os.path.abspath(".."))

import torch
from scripts.zeroshot_llama import load_model, run_zeroshot

# Configuration
MODEL_ID = "meta-llama/Llama-3.2-11B-Vision-Instruct"
DATA_ROOT = os.path.abspath("../data")
OUTPUT_DIR = os.path.abspath("../results/zeroshot")

def cleanup(*vars_to_del):
    """Delete prediction variables and free GPU memory."""
    for v in vars_to_del:
        del v
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# Load model once — reused across all 12 experiments
model, processor = load_model(MODEL_ID)

Loading model: meta-llama/Llama-3.2-11B-Vision-Instruct

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

Model loaded on cuda:0

In [ ]:
import json as _json
import pandas as pd
from pathlib import Path as _Path
from scripts.zeroshot_llama import model_slug

def show_summary(task):
    slug = model_slug(MODEL_ID)
    results_dir = _Path(OUTPUT_DIR) / slug / task
    modalities = ["text_only", "image_only", "text_image"]
    splits = ["test", "train"]
    rows = []
    for modality in modalities:
        for split in splits:
            metrics_path = results_dir / modality / split / "metrics.json"
            if metrics_path.exists():
                m = _json.loads(metrics_path.read_text())
                rows.append({
                    "Modality": m["modality"], "Split": m["split"],
                    "Samples": m["num_samples"],
                    "Accuracy": f"{m['accuracy']:.4f}",
                    "Weighted F1": f"{m['weighted_f1']:.4f}",
                    "Macro F1": f"{m['macro_f1']:.4f}",
                    "Unparseable": m["num_unparseable"],
                })
            else:
                rows.append({
                    "Modality": modality, "Split": split,
                    "Samples": "-", "Accuracy": "-",
                    "Weighted F1": "-", "Macro F1": "-", "Unparseable": "-",
                })
    print(f"Task: {task}")
    print(f"Model: {slug}\n")
    display(pd.DataFrame(rows))

## Informative Task (6 experiments)

## 1. Text-Only -- Test Set

In [2]:
# 1. Informative — text_only — test
preds, _ = run_zeroshot(
    task="informative", modality="text_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_only\test.tsv
  [50/1534] 15s elapsed, ~457s remaining, 3.2 samples/s
  [100/1534] 30s elapsed, ~429s remaining, 3.3 samples/s
  [150/1534] 45s elapsed, ~411s remaining, 3.4 samples/s
  [200/1534] 59s elapsed, ~392s remaining, 3.4 samples/s
  [250/1534] 73s elapsed, ~377s remaining, 3.4 samples/s
  [300/1534] 88s elapsed, ~362s remaining, 3.4 samples/s
  [350/1534] 103s elapsed, ~347s remaining, 3.4 samples/s
  [400/1534] 117s elapsed, ~332s remaining, 3.4 samples/s
  [450/1534] 132s elapsed, ~317s remaining, 3.4 samples/s
  [500/1534] 147s elapsed, ~303s remaining, 3.4 samples/s
  [550/1534] 161s elapsed, ~288s remaining, 3.4 samples/s
  [600/1534] 176s elapsed, ~273s remaining, 3.4 samples/s
  [650/1534] 190s elapsed, ~259s remaining, 3.4 samples/s
  [700/1534] 205s elapsed, ~244s remaining, 3.4 samples/s
  [750/1534] 219s elapsed, ~229s remaining, 3.4 samples/s
  [800/1534] 234s elapsed, ~215s remaining, 3.4 samples/s
  [850/1534] 248s elapsed, ~200s remaining, 3.4 samples/s
  [900/1534] 263s elapsed, ~185s remaining, 3.4 samples/s
  [950/1534] 278s elapsed, ~171s remaining, 3.4 samples/s
  [1000/1534] 293s elapsed, ~156s remaining, 3.4 samples/s
  [1050/1534] 307s elapsed, ~142s remaining, 3.4 samples/s
  [1100/1534] 322s elapsed, ~127s remaining, 3.4 samples/s
  [1150/1534] 336s elapsed, ~112s remaining, 3.4 samples/s
  [1200/1534] 351s elapsed, ~98s remaining, 3.4 samples/s
  [1250/1534] 365s elapsed, ~83s remaining, 3.4 samples/s
  [1300/1534] 380s elapsed, ~68s remaining, 3.4 samples/s
  [1350/1534] 395s elapsed, ~54s remaining, 3.4 samples/s
  [1400/1534] 409s elapsed, ~39s remaining, 3.4 samples/s
  [1450/1534] 424s elapsed, ~25s remaining, 3.4 samples/s
  [1500/1534] 438s elapsed, ~10s remaining, 3.4 samples/s
  [1534/1534] 447s elapsed, ~0s remaining, 3.4 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\text_only\test
  Accuracy:           0.8357
  Weighted Precision: 0.8332
  Weighted Recall:    0.8357
  Weighted F1:        0.8311
  Macro Precision:    0.8258
  Macro Recall:       0.7910
  Macro F1:           0.8041
  Unparseable:        0

## 2. Text-Only -- Train Set

In [3]:
# 2. Informative — text_only — train
preds, _ = run_zeroshot(
    task="informative", modality="text_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 8293 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_only\train.tsv
  [50/8293] 14s elapsed, ~2381s remaining, 3.5 samples/s
  [100/8293] 29s elapsed, ~2362s remaining, 3.5 samples/s
  [150/8293] 44s elapsed, ~2365s remaining, 3.4 samples/s
  [200/8293] 58s elapsed, ~2337s remaining, 3.5 samples/s
  [250/8293] 72s elapsed, ~2318s remaining, 3.5 samples/s
  [300/8293] 86s elapsed, ~2302s remaining, 3.5 samples/s
  [350/8293] 100s elapsed, ~2278s remaining, 3.5 samples/s
  [400/8293] 115s elapsed, ~2261s remaining, 3.5 samples/s
  [450/8293] 129s elapsed, ~2242s remaining, 3.5 samples/s
  [500/8293] 143s elapsed, ~2230s remaining, 3.5 samples/s
  [550/8293] 157s elapsed, ~2216s remaining, 3.5 samples/s
  [600/8293] 171s elapsed, ~2199s remaining, 3.5 samples/s
  [650/8293] 186s elapsed, ~2187s remaining, 3.5 samples/s
  [700/8293] 200s elapsed, ~2172s remaining, 3.5 samples/s
  [750/8293] 214s elapsed, ~2155s remaining, 3.5 samples/s
  [800/8293] 229s elapsed, ~2143s remaining, 3.5 samples/s
  [850/8293] 243s elapsed, ~2129s remaining, 3.5 samples/s
  [900/8293] 257s elapsed, ~2114s remaining, 3.5 samples/s
  [950/8293] 271s elapsed, ~2098s remaining, 3.5 samples/s
  [1000/8293] 286s elapsed, ~2086s remaining, 3.5 samples/s
  [1050/8293] 300s elapsed, ~2072s remaining, 3.5 samples/s
  [1100/8293] 315s elapsed, ~2057s remaining, 3.5 samples/s
  [1150/8293] 329s elapsed, ~2045s remaining, 3.5 samples/s
  [1200/8293] 343s elapsed, ~2030s remaining, 3.5 samples/s
  [1250/8293] 357s elapsed, ~2013s remaining, 3.5 samples/s
  [1300/8293] 372s elapsed, ~1998s remaining, 3.5 samples/s
  [1350/8293] 386s elapsed, ~1985s remaining, 3.5 samples/s
  [1400/8293] 400s elapsed, ~1970s remaining, 3.5 samples/s
  [1450/8293] 414s elapsed, ~1955s remaining, 3.5 samples/s
  [1500/8293] 429s elapsed, ~1941s remaining, 3.5 samples/s
  [1550/8293] 443s elapsed, ~1929s remaining, 3.5 samples/s
  [1600/8293] 458s elapsed, ~1914s remaining, 3.5 samples/s
  [1650/8293] 472s elapsed, ~1900s remaining, 3.5 samples/s
  [1700/8293] 486s elapsed, ~1886s remaining, 3.5 samples/s
  [1750/8293] 500s elapsed, ~1871s remaining, 3.5 samples/s
  [1800/8293] 514s elapsed, ~1855s remaining, 3.5 samples/s
  [1850/8293] 528s elapsed, ~1841s remaining, 3.5 samples/s
  [1900/8293] 542s elapsed, ~1825s remaining, 3.5 samples/s
  [1950/8293] 556s elapsed, ~1809s remaining, 3.5 samples/s
  [2000/8293] 570s elapsed, ~1795s remaining, 3.5 samples/s
  [2050/8293] 584s elapsed, ~1780s remaining, 3.5 samples/s
  [2100/8293] 598s elapsed, ~1764s remaining, 3.5 samples/s
  [2150/8293] 612s elapsed, ~1749s remaining, 3.5 samples/s
  [2200/8293] 626s elapsed, ~1733s remaining, 3.5 samples/s
  [2250/8293] 640s elapsed, ~1719s remaining, 3.5 samples/s
  [2300/8293] 654s elapsed, ~1704s remaining, 3.5 samples/s
  [2350/8293] 668s elapsed, ~1689s remaining, 3.5 samples/s
  [2400/8293] 682s elapsed, ~1673s remaining, 3.5 samples/s
  [2450/8293] 695s elapsed, ~1658s remaining, 3.5 samples/s
  [2500/8293] 709s elapsed, ~1644s remaining, 3.5 samples/s
  [2550/8293] 724s elapsed, ~1630s remaining, 3.5 samples/s
  [2600/8293] 737s elapsed, ~1615s remaining, 3.5 samples/s
  [2650/8293] 751s elapsed, ~1600s remaining, 3.5 samples/s
  [2700/8293] 766s elapsed, ~1586s remaining, 3.5 samples/s
  [2750/8293] 780s elapsed, ~1571s remaining, 3.5 samples/s
  [2800/8293] 794s elapsed, ~1557s remaining, 3.5 samples/s
  [2850/8293] 807s elapsed, ~1542s remaining, 3.5 samples/s
  [2900/8293] 821s elapsed, ~1528s remaining, 3.5 samples/s
  [2950/8293] 835s elapsed, ~1512s remaining, 3.5 samples/s
  [3000/8293] 846s elapsed, ~1493s remaining, 3.5 samples/s
  [3050/8293] 859s elapsed, ~1476s remaining, 3.6 samples/s
  [3100/8293] 871s elapsed, ~1460s remaining, 3.6 samples/s
  [3150/8293] 884s elapsed, ~1443s remaining, 3.6 samples/s
  [3200/8293] 896s elapsed, ~1426s remaining, 3.6 samples/s
  [3250/8293] 909s elapsed, ~1410s remaining, 3.6 samples/s
  [3300/8293] 921s elapsed, ~1393s remaining, 3.6 samples/s
  [3350/8293] 933s elapsed, ~1377s remaining, 3.6 samples/s
  [3400/8293] 946s elapsed, ~1361s remaining, 3.6 samples/s
  [3450/8293] 958s elapsed, ~1345s remaining, 3.6 samples/s
  [3500/8293] 970s elapsed, ~1329s remaining, 3.6 samples/s
  [3550/8293] 983s elapsed, ~1313s remaining, 3.6 samples/s
  [3600/8293] 995s elapsed, ~1297s remaining, 3.6 samples/s
  [3650/8293] 1007s elapsed, ~1281s remaining, 3.6 samples/s
  [3700/8293] 1020s elapsed, ~1266s remaining, 3.6 samples/s
  [3750/8293] 1032s elapsed, ~1250s remaining, 3.6 samples/s
  [3800/8293] 1045s elapsed, ~1235s remaining, 3.6 samples/s
  [3850/8293] 1057s elapsed, ~1220s remaining, 3.6 samples/s
  [3900/8293] 1069s elapsed, ~1204s remaining, 3.6 samples/s
  [3950/8293] 1082s elapsed, ~1189s remaining, 3.7 samples/s
  [4000/8293] 1094s elapsed, ~1174s remaining, 3.7 samples/s
  [4050/8293] 1106s elapsed, ~1159s remaining, 3.7 samples/s
  [4100/8293] 1116s elapsed, ~1142s remaining, 3.7 samples/s
  [4150/8293] 1126s elapsed, ~1125s remaining, 3.7 samples/s
  [4200/8293] 1137s elapsed, ~1108s remaining, 3.7 samples/s
  [4250/8293] 1146s elapsed, ~1091s remaining, 3.7 samples/s
  [4300/8293] 1156s elapsed, ~1074s remaining, 3.7 samples/s
  [4350/8293] 1166s elapsed, ~1057s remaining, 3.7 samples/s
  [4400/8293] 1176s elapsed, ~1041s remaining, 3.7 samples/s
  [4450/8293] 1187s elapsed, ~1025s remaining, 3.8 samples/s
  [4500/8293] 1197s elapsed, ~1009s remaining, 3.8 samples/s
  [4550/8293] 1207s elapsed, ~993s remaining, 3.8 samples/s
  [4600/8293] 1217s elapsed, ~977s remaining, 3.8 samples/s
  [4650/8293] 1227s elapsed, ~961s remaining, 3.8 samples/s
  [4700/8293] 1237s elapsed, ~945s remaining, 3.8 samples/s
  [4750/8293] 1247s elapsed, ~930s remaining, 3.8 samples/s
  [4800/8293] 1257s elapsed, ~915s remaining, 3.8 samples/s
  [4850/8293] 1267s elapsed, ~899s remaining, 3.8 samples/s
  [4900/8293] 1277s elapsed, ~884s remaining, 3.8 samples/s
  [4950/8293] 1287s elapsed, ~869s remaining, 3.8 samples/s
  [5000/8293] 1297s elapsed, ~854s remaining, 3.9 samples/s
  [5050/8293] 1307s elapsed, ~839s remaining, 3.9 samples/s
  [5100/8293] 1317s elapsed, ~824s remaining, 3.9 samples/s
  [5150/8293] 1327s elapsed, ~810s remaining, 3.9 samples/s
  [5200/8293] 1336s elapsed, ~795s remaining, 3.9 samples/s
  [5250/8293] 1346s elapsed, ~780s remaining, 3.9 samples/s
  [5300/8293] 1356s elapsed, ~766s remaining, 3.9 samples/s
  [5350/8293] 1366s elapsed, ~752s remaining, 3.9 samples/s
  [5400/8293] 1376s elapsed, ~737s remaining, 3.9 samples/s
  [5450/8293] 1386s elapsed, ~723s remaining, 3.9 samples/s
  [5500/8293] 1396s elapsed, ~709s remaining, 3.9 samples/s
  [5550/8293] 1407s elapsed, ~695s remaining, 3.9 samples/s
  [5600/8293] 1417s elapsed, ~681s remaining, 4.0 samples/s
  [5650/8293] 1427s elapsed, ~667s remaining, 4.0 samples/s
  [5700/8293] 1437s elapsed, ~654s remaining, 4.0 samples/s
  [5750/8293] 1447s elapsed, ~640s remaining, 4.0 samples/s
  [5800/8293] 1457s elapsed, ~626s remaining, 4.0 samples/s
  [5850/8293] 1467s elapsed, ~613s remaining, 4.0 samples/s
  [5900/8293] 1477s elapsed, ~599s remaining, 4.0 samples/s
  [5950/8293] 1486s elapsed, ~585s remaining, 4.0 samples/s
  [6000/8293] 1496s elapsed, ~572s remaining, 4.0 samples/s
  [6050/8293] 1506s elapsed, ~558s remaining, 4.0 samples/s
  [6100/8293] 1516s elapsed, ~545s remaining, 4.0 samples/s
  [6150/8293] 1526s elapsed, ~532s remaining, 4.0 samples/s
  [6200/8293] 1536s elapsed, ~518s remaining, 4.0 samples/s
  [6250/8293] 1545s elapsed, ~505s remaining, 4.0 samples/s
  [6300/8293] 1555s elapsed, ~492s remaining, 4.1 samples/s
  [6350/8293] 1565s elapsed, ~479s remaining, 4.1 samples/s
  [6400/8293] 1575s elapsed, ~466s remaining, 4.1 samples/s
  [6450/8293] 1585s elapsed, ~453s remaining, 4.1 samples/s
  [6500/8293] 1595s elapsed, ~440s remaining, 4.1 samples/s
  [6550/8293] 1605s elapsed, ~427s remaining, 4.1 samples/s
  [6600/8293] 1615s elapsed, ~414s remaining, 4.1 samples/s
  [6650/8293] 1625s elapsed, ~401s remaining, 4.1 samples/s
  [6700/8293] 1635s elapsed, ~389s remaining, 4.1 samples/s
  [6750/8293] 1645s elapsed, ~376s remaining, 4.1 samples/s
  [6800/8293] 1655s elapsed, ~363s remaining, 4.1 samples/s
  [6850/8293] 1665s elapsed, ~351s remaining, 4.1 samples/s
  [6900/8293] 1675s elapsed, ~338s remaining, 4.1 samples/s
  [6950/8293] 1685s elapsed, ~326s remaining, 4.1 samples/s
  [7000/8293] 1695s elapsed, ~313s remaining, 4.1 samples/s
  [7050/8293] 1704s elapsed, ~300s remaining, 4.1 samples/s
  [7100/8293] 1714s elapsed, ~288s remaining, 4.1 samples/s
  [7150/8293] 1724s elapsed, ~276s remaining, 4.1 samples/s
  [7200/8293] 1734s elapsed, ~263s remaining, 4.2 samples/s
  [7250/8293] 1744s elapsed, ~251s remaining, 4.2 samples/s
  [7300/8293] 1753s elapsed, ~238s remaining, 4.2 samples/s
  [7350/8293] 1762s elapsed, ~226s remaining, 4.2 samples/s
  [7400/8293] 1772s elapsed, ~214s remaining, 4.2 samples/s
  [7450/8293] 1782s elapsed, ~202s remaining, 4.2 samples/s
  [7500/8293] 1791s elapsed, ~189s remaining, 4.2 samples/s
  [7550/8293] 1801s elapsed, ~177s remaining, 4.2 samples/s
  [7600/8293] 1810s elapsed, ~165s remaining, 4.2 samples/s
  [7650/8293] 1820s elapsed, ~153s remaining, 4.2 samples/s
  [7700/8293] 1829s elapsed, ~141s remaining, 4.2 samples/s
  [7750/8293] 1839s elapsed, ~129s remaining, 4.2 samples/s
  [7800/8293] 1849s elapsed, ~117s remaining, 4.2 samples/s
  [7850/8293] 1859s elapsed, ~105s remaining, 4.2 samples/s
  [7900/8293] 1869s elapsed, ~93s remaining, 4.2 samples/s
  [7950/8293] 1878s elapsed, ~81s remaining, 4.2 samples/s
  [8000/8293] 1888s elapsed, ~69s remaining, 4.2 samples/s
  [8050/8293] 1898s elapsed, ~57s remaining, 4.2 samples/s
  [8100/8293] 1907s elapsed, ~45s remaining, 4.2 samples/s
  [8150/8293] 1917s elapsed, ~34s remaining, 4.3 samples/s
  [8200/8293] 1926s elapsed, ~22s remaining, 4.3 samples/s
  [8250/8293] 1936s elapsed, ~10s remaining, 4.3 samples/s
  [8293/8293] 1945s elapsed, ~0s remaining, 4.3 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\text_only\train
  Accuracy:           0.8184
  Weighted Precision: 0.8148
  Weighted Recall:    0.8184
  Weighted F1:        0.8141
  Macro Precision:    0.8029
  Macro Recall:       0.7754
  Macro F1:           0.7860
  Unparseable:        0

## 3. Image-Only -- Test Set

In [4]:
# 3. Informative — image_only — test
preds, _ = run_zeroshot(
    task="informative", modality="image_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\image_only\test.tsv
  [50/1534] 39s elapsed, ~1163s remaining, 1.3 samples/s
  [100/1534] 77s elapsed, ~1111s remaining, 1.3 samples/s
  [150/1534] 117s elapsed, ~1078s remaining, 1.3 samples/s
  [200/1534] 155s elapsed, ~1033s remaining, 1.3 samples/s
  [250/1534] 193s elapsed, ~992s remaining, 1.3 samples/s
  [300/1534] 231s elapsed, ~952s remaining, 1.3 samples/s
  [350/1534] 269s elapsed, ~912s remaining, 1.3 samples/s
  [400/1534] 307s elapsed, ~872s remaining, 1.3 samples/s
  [450/1534] 346s elapsed, ~833s remaining, 1.3 samples/s
  [500/1534] 385s elapsed, ~796s remaining, 1.3 samples/s
  [550/1534] 423s elapsed, ~756s remaining, 1.3 samples/s
  [600/1534] 461s elapsed, ~717s remaining, 1.3 samples/s
  [650/1534] 499s elapsed, ~678s remaining, 1.3 samples/s
  [700/1534] 537s elapsed, ~640s remaining, 1.3 samples/s
  [750/1534] 576s elapsed, ~602s remaining, 1.3 samples/s
  [800/1534] 614s elapsed, ~563s remaining, 1.3 samples/s
  [850/1534] 652s elapsed, ~525s remaining, 1.3 samples/s
  [900/1534] 690s elapsed, ~486s remaining, 1.3 samples/s
  [950/1534] 729s elapsed, ~448s remaining, 1.3 samples/s
  [1000/1534] 767s elapsed, ~410s remaining, 1.3 samples/s
  [1050/1534] 805s elapsed, ~371s remaining, 1.3 samples/s
  [1100/1534] 842s elapsed, ~332s remaining, 1.3 samples/s
  [1150/1534] 880s elapsed, ~294s remaining, 1.3 samples/s
  [1200/1534] 918s elapsed, ~256s remaining, 1.3 samples/s
  [1250/1534] 956s elapsed, ~217s remaining, 1.3 samples/s
  [1300/1534] 994s elapsed, ~179s remaining, 1.3 samples/s
  [1350/1534] 1032s elapsed, ~141s remaining, 1.3 samples/s
  [1400/1534] 1070s elapsed, ~102s remaining, 1.3 samples/s
  [1450/1534] 1108s elapsed, ~64s remaining, 1.3 samples/s
  [1500/1534] 1146s elapsed, ~26s remaining, 1.3 samples/s
  [1534/1534] 1172s elapsed, ~0s remaining, 1.3 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\image_only\test
  Accuracy:           0.8605
  Weighted Precision: 0.8630
  Weighted Recall:    0.8605
  Weighted F1:        0.8546
  Macro Precision:    0.8683
  Macro Recall:       0.8100
  Macro F1:           0.8297
  Unparseable:        0

## 4. Image-Only -- Train Set

In [5]:
# 4. Informative — image_only — train
preds, _ = run_zeroshot(
    task="informative", modality="image_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 9601 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\image_only\train.tsv
  [50/9601] 38s elapsed, ~7341s remaining, 1.3 samples/s
  [100/9601] 76s elapsed, ~7260s remaining, 1.3 samples/s
  [150/9601] 114s elapsed, ~7199s remaining, 1.3 samples/s
  [200/9601] 153s elapsed, ~7182s remaining, 1.3 samples/s
  [250/9601] 191s elapsed, ~7154s remaining, 1.3 samples/s
  [300/9601] 229s elapsed, ~7109s remaining, 1.3 samples/s
  [350/9601] 268s elapsed, ~7088s remaining, 1.3 samples/s
  [400/9601] 307s elapsed, ~7059s remaining, 1.3 samples/s
  [450/9601] 345s elapsed, ~7023s remaining, 1.3 samples/s
  [500/9601] 384s elapsed, ~6995s remaining, 1.3 samples/s
  [550/9601] 426s elapsed, ~7002s remaining, 1.3 samples/s
  [600/9601] 464s elapsed, ~6958s remaining, 1.3 samples/s
  [650/9601] 502s elapsed, ~6917s remaining, 1.3 samples/s
  [700/9601] 543s elapsed, ~6900s remaining, 1.3 samples/s
  [750/9601] 582s elapsed, ~6863s remaining, 1.3 samples/s
  [800/9601] 620s elapsed, ~6821s remaining, 1.3 samples/s
  [850/9601] 658s elapsed, ~6779s remaining, 1.3 samples/s
  [900/9601] 697s elapsed, ~6741s remaining, 1.3 samples/s
  [950/9601] 738s elapsed, ~6717s remaining, 1.3 samples/s
  [1000/9601] 778s elapsed, ~6689s remaining, 1.3 samples/s
  [1050/9601] 816s elapsed, ~6649s remaining, 1.3 samples/s
  [1100/9601] 855s elapsed, ~6609s remaining, 1.3 samples/s
  [1150/9601] 894s elapsed, ~6568s remaining, 1.3 samples/s
  [1200/9601] 932s elapsed, ~6526s remaining, 1.3 samples/s
  [1250/9601] 971s elapsed, ~6484s remaining, 1.3 samples/s
  [1300/9601] 1009s elapsed, ~6444s remaining, 1.3 samples/s
  [1350/9601] 1052s elapsed, ~6431s remaining, 1.3 samples/s
  [1400/9601] 1091s elapsed, ~6392s remaining, 1.3 samples/s
  [1450/9601] 1129s elapsed, ~6349s remaining, 1.3 samples/s
  [1500/9601] 1168s elapsed, ~6308s remaining, 1.3 samples/s
  [1550/9601] 1211s elapsed, ~6289s remaining, 1.3 samples/s
  [1600/9601] 1250s elapsed, ~6251s remaining, 1.3 samples/s
  [1650/9601] 1289s elapsed, ~6209s remaining, 1.3 samples/s
  [1700/9601] 1327s elapsed, ~6169s remaining, 1.3 samples/s
  [1750/9601] 1366s elapsed, ~6129s remaining, 1.3 samples/s
  [1800/9601] 1406s elapsed, ~6092s remaining, 1.3 samples/s
  [1850/9601] 1447s elapsed, ~6062s remaining, 1.3 samples/s
  [1900/9601] 1486s elapsed, ~6022s remaining, 1.3 samples/s
  [1950/9601] 1524s elapsed, ~5981s remaining, 1.3 samples/s
  [2000/9601] 1563s elapsed, ~5941s remaining, 1.3 samples/s
  [2050/9601] 1602s elapsed, ~5900s remaining, 1.3 samples/s
  [2100/9601] 1641s elapsed, ~5860s remaining, 1.3 samples/s
  [2150/9601] 1679s elapsed, ~5820s remaining, 1.3 samples/s
  [2200/9601] 1718s elapsed, ~5780s remaining, 1.3 samples/s
  [2250/9601] 1757s elapsed, ~5740s remaining, 1.3 samples/s
  [2300/9601] 1795s elapsed, ~5698s remaining, 1.3 samples/s
  [2350/9601] 1835s elapsed, ~5662s remaining, 1.3 samples/s
  [2400/9601] 1874s elapsed, ~5623s remaining, 1.3 samples/s
  [2450/9601] 1912s elapsed, ~5580s remaining, 1.3 samples/s
  [2500/9601] 1950s elapsed, ~5539s remaining, 1.3 samples/s
  [2550/9601] 1988s elapsed, ~5497s remaining, 1.3 samples/s
  [2600/9601] 2026s elapsed, ~5456s remaining, 1.3 samples/s
  [2650/9601] 2065s elapsed, ~5416s remaining, 1.3 samples/s
  [2700/9601] 2104s elapsed, ~5378s remaining, 1.3 samples/s
  [2750/9601] 2142s elapsed, ~5337s remaining, 1.3 samples/s
  [2800/9601] 2180s elapsed, ~5295s remaining, 1.3 samples/s
  [2850/9601] 2218s elapsed, ~5254s remaining, 1.3 samples/s
  [2900/9601] 2256s elapsed, ~5213s remaining, 1.3 samples/s
  [2950/9601] 2294s elapsed, ~5173s remaining, 1.3 samples/s
  [3000/9601] 2332s elapsed, ~5131s remaining, 1.3 samples/s
  [3050/9601] 2370s elapsed, ~5091s remaining, 1.3 samples/s
  [3100/9601] 2409s elapsed, ~5051s remaining, 1.3 samples/s
  [3150/9601] 2447s elapsed, ~5011s remaining, 1.3 samples/s
  [3200/9601] 2488s elapsed, ~4977s remaining, 1.3 samples/s
  [3250/9601] 2527s elapsed, ~4939s remaining, 1.3 samples/s
  [3300/9601] 2567s elapsed, ~4902s remaining, 1.3 samples/s
  [3350/9601] 2612s elapsed, ~4875s remaining, 1.3 samples/s
  [3400/9601] 2656s elapsed, ~4844s remaining, 1.3 samples/s
  [3450/9601] 2703s elapsed, ~4819s remaining, 1.3 samples/s
  [3500/9601] 2750s elapsed, ~4794s remaining, 1.3 samples/s
  [3550/9601] 2796s elapsed, ~4766s remaining, 1.3 samples/s
  [3600/9601] 2843s elapsed, ~4739s remaining, 1.3 samples/s
  [3650/9601] 2893s elapsed, ~4717s remaining, 1.3 samples/s
  [3700/9601] 2941s elapsed, ~4690s remaining, 1.3 samples/s
  [3750/9601] 2992s elapsed, ~4668s remaining, 1.3 samples/s
  [3800/9601] 3043s elapsed, ~4645s remaining, 1.2 samples/s
  [3850/9601] 3091s elapsed, ~4618s remaining, 1.2 samples/s
  [3900/9601] 3140s elapsed, ~4590s remaining, 1.2 samples/s
  [3950/9601] 3191s elapsed, ~4565s remaining, 1.2 samples/s
  [4000/9601] 3238s elapsed, ~4534s remaining, 1.2 samples/s
  [4050/9601] 3284s elapsed, ~4502s remaining, 1.2 samples/s
  [4100/9601] 3332s elapsed, ~4470s remaining, 1.2 samples/s
  [4150/9601] 3380s elapsed, ~4439s remaining, 1.2 samples/s
  [4200/9601] 3430s elapsed, ~4411s remaining, 1.2 samples/s
  [4250/9601] 3480s elapsed, ~4381s remaining, 1.2 samples/s
  [4300/9601] 3528s elapsed, ~4349s remaining, 1.2 samples/s
  [4350/9601] 3577s elapsed, ~4318s remaining, 1.2 samples/s
  [4400/9601] 3628s elapsed, ~4289s remaining, 1.2 samples/s
  [4450/9601] 3677s elapsed, ~4256s remaining, 1.2 samples/s
  [4500/9601] 3727s elapsed, ~4224s remaining, 1.2 samples/s
  [4550/9601] 3774s elapsed, ~4190s remaining, 1.2 samples/s
  [4600/9601] 3828s elapsed, ~4162s remaining, 1.2 samples/s
  [4650/9601] 3876s elapsed, ~4127s remaining, 1.2 samples/s
  [4700/9601] 3927s elapsed, ~4095s remaining, 1.2 samples/s
  [4750/9601] 3974s elapsed, ~4059s remaining, 1.2 samples/s
  [4800/9601] 4022s elapsed, ~4023s remaining, 1.2 samples/s
  [4850/9601] 4071s elapsed, ~3988s remaining, 1.2 samples/s
  [4900/9601] 4120s elapsed, ~3953s remaining, 1.2 samples/s
  [4950/9601] 4171s elapsed, ~3919s remaining, 1.2 samples/s
  [5000/9601] 4222s elapsed, ~3885s remaining, 1.2 samples/s
  [5050/9601] 4271s elapsed, ~3849s remaining, 1.2 samples/s
  [5100/9601] 4321s elapsed, ~3813s remaining, 1.2 samples/s
  [5150/9601] 4368s elapsed, ~3775s remaining, 1.2 samples/s
  [5200/9601] 4421s elapsed, ~3742s remaining, 1.2 samples/s
  [5250/9601] 4470s elapsed, ~3704s remaining, 1.2 samples/s
  [5300/9601] 4523s elapsed, ~3670s remaining, 1.2 samples/s
  [5350/9601] 4570s elapsed, ~3632s remaining, 1.2 samples/s
  [5400/9601] 4620s elapsed, ~3595s remaining, 1.2 samples/s
  [5450/9601] 4667s elapsed, ~3555s remaining, 1.2 samples/s
  [5500/9601] 4715s elapsed, ~3516s remaining, 1.2 samples/s
  [5550/9601] 4762s elapsed, ~3476s remaining, 1.2 samples/s
  [5600/9601] 4811s elapsed, ~3437s remaining, 1.2 samples/s
  [5650/9601] 4856s elapsed, ~3396s remaining, 1.2 samples/s
  [5700/9601] 4900s elapsed, ~3353s remaining, 1.2 samples/s
  [5750/9601] 4943s elapsed, ~3310s remaining, 1.2 samples/s
  [5800/9601] 4983s elapsed, ~3266s remaining, 1.2 samples/s
  [5850/9601] 5022s elapsed, ~3220s remaining, 1.2 samples/s
  [5900/9601] 5061s elapsed, ~3174s remaining, 1.2 samples/s
  [5950/9601] 5099s elapsed, ~3129s remaining, 1.2 samples/s
  [6000/9601] 5137s elapsed, ~3083s remaining, 1.2 samples/s
  [6050/9601] 5176s elapsed, ~3038s remaining, 1.2 samples/s
  [6100/9601] 5216s elapsed, ~2994s remaining, 1.2 samples/s
  [6150/9601] 5257s elapsed, ~2950s remaining, 1.2 samples/s
  [6200/9601] 5297s elapsed, ~2905s remaining, 1.2 samples/s
  [6250/9601] 5337s elapsed, ~2862s remaining, 1.2 samples/s
  [6300/9601] 5375s elapsed, ~2817s remaining, 1.2 samples/s
  [6350/9601] 5414s elapsed, ~2772s remaining, 1.2 samples/s
  [6400/9601] 5455s elapsed, ~2728s remaining, 1.2 samples/s
  [6450/9601] 5500s elapsed, ~2687s remaining, 1.2 samples/s
  [6500/9601] 5551s elapsed, ~2648s remaining, 1.2 samples/s
  [6550/9601] 5599s elapsed, ~2608s remaining, 1.2 samples/s
  [6600/9601] 5646s elapsed, ~2567s remaining, 1.2 samples/s
  [6650/9601] 5695s elapsed, ~2527s remaining, 1.2 samples/s
  [6700/9601] 5745s elapsed, ~2487s remaining, 1.2 samples/s
  [6750/9601] 5791s elapsed, ~2446s remaining, 1.2 samples/s
  [6800/9601] 5837s elapsed, ~2404s remaining, 1.2 samples/s
  [6850/9601] 5886s elapsed, ~2364s remaining, 1.2 samples/s
  [6900/9601] 5933s elapsed, ~2322s remaining, 1.2 samples/s
  [6950/9601] 5980s elapsed, ~2281s remaining, 1.2 samples/s
  [7000/9601] 6031s elapsed, ~2241s remaining, 1.2 samples/s
  [7050/9601] 6078s elapsed, ~2199s remaining, 1.2 samples/s
  [7100/9601] 6125s elapsed, ~2158s remaining, 1.2 samples/s
  [7150/9601] 6174s elapsed, ~2116s remaining, 1.2 samples/s
  [7200/9601] 6221s elapsed, ~2074s remaining, 1.2 samples/s
  [7250/9601] 6268s elapsed, ~2032s remaining, 1.2 samples/s
  [7300/9601] 6315s elapsed, ~1991s remaining, 1.2 samples/s
  [7350/9601] 6362s elapsed, ~1948s remaining, 1.2 samples/s
  [7400/9601] 6409s elapsed, ~1906s remaining, 1.2 samples/s
  [7450/9601] 6456s elapsed, ~1864s remaining, 1.2 samples/s
  [7500/9601] 6505s elapsed, ~1822s remaining, 1.2 samples/s
  [7550/9601] 6552s elapsed, ~1780s remaining, 1.2 samples/s
  [7600/9601] 6598s elapsed, ~1737s remaining, 1.2 samples/s
  [7650/9601] 6644s elapsed, ~1694s remaining, 1.2 samples/s
  [7700/9601] 6690s elapsed, ~1652s remaining, 1.2 samples/s
  [7750/9601] 6737s elapsed, ~1609s remaining, 1.2 samples/s
  [7800/9601] 6783s elapsed, ~1566s remaining, 1.2 samples/s
  [7850/9601] 6829s elapsed, ~1523s remaining, 1.1 samples/s
  [7900/9601] 6875s elapsed, ~1480s remaining, 1.1 samples/s
  [7950/9601] 6923s elapsed, ~1438s remaining, 1.1 samples/s
  [8000/9601] 6971s elapsed, ~1395s remaining, 1.1 samples/s
  [8050/9601] 7018s elapsed, ~1352s remaining, 1.1 samples/s
  [8100/9601] 7066s elapsed, ~1309s remaining, 1.1 samples/s
  [8150/9601] 7112s elapsed, ~1266s remaining, 1.1 samples/s
  [8200/9601] 7158s elapsed, ~1223s remaining, 1.1 samples/s
  [8250/9601] 7204s elapsed, ~1180s remaining, 1.1 samples/s
  [8300/9601] 7251s elapsed, ~1137s remaining, 1.1 samples/s
  [8350/9601] 7298s elapsed, ~1093s remaining, 1.1 samples/s
  [8400/9601] 7344s elapsed, ~1050s remaining, 1.1 samples/s
  [8450/9601] 7392s elapsed, ~1007s remaining, 1.1 samples/s
  [8500/9601] 7441s elapsed, ~964s remaining, 1.1 samples/s
  [8550/9601] 7487s elapsed, ~920s remaining, 1.1 samples/s
  [8600/9601] 7533s elapsed, ~877s remaining, 1.1 samples/s
  [8650/9601] 7580s elapsed, ~833s remaining, 1.1 samples/s
  [8700/9601] 7627s elapsed, ~790s remaining, 1.1 samples/s
  [8750/9601] 7672s elapsed, ~746s remaining, 1.1 samples/s
  [8800/9601] 7715s elapsed, ~702s remaining, 1.1 samples/s
  [8850/9601] 7757s elapsed, ~658s remaining, 1.1 samples/s
  [8900/9601] 7798s elapsed, ~614s remaining, 1.1 samples/s
  [8950/9601] 7838s elapsed, ~570s remaining, 1.1 samples/s
  [9000/9601] 7877s elapsed, ~526s remaining, 1.1 samples/s
  [9050/9601] 7916s elapsed, ~482s remaining, 1.1 samples/s
  [9100/9601] 7955s elapsed, ~438s remaining, 1.1 samples/s
  [9150/9601] 7992s elapsed, ~394s remaining, 1.1 samples/s
  [9200/9601] 8030s elapsed, ~350s remaining, 1.1 samples/s
  [9250/9601] 8068s elapsed, ~306s remaining, 1.1 samples/s
  [9300/9601] 8106s elapsed, ~262s remaining, 1.1 samples/s
  [9350/9601] 8145s elapsed, ~219s remaining, 1.1 samples/s
  [9400/9601] 8183s elapsed, ~175s remaining, 1.1 samples/s
  [9450/9601] 8222s elapsed, ~131s remaining, 1.1 samples/s
  [9500/9601] 8262s elapsed, ~88s remaining, 1.1 samples/s
  [9550/9601] 8300s elapsed, ~44s remaining, 1.2 samples/s
  [9600/9601] 8340s elapsed, ~1s remaining, 1.2 samples/s
  [9601/9601] 8341s elapsed, ~0s remaining, 1.2 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\image_only\train
  Accuracy:           0.8591
  Weighted Precision: 0.8616
  Weighted Recall:    0.8591
  Weighted F1:        0.8537
  Macro Precision:    0.8666
  Macro Recall:       0.8141
  Macro F1:           0.8320
  Unparseable:        0

## 5. Text+Image -- Test Set

In [6]:
# 5. Informative — text_image — test
preds, _ = run_zeroshot(
    task="informative", modality="text_image", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_image\test.tsv
  [50/1534] 46s elapsed, ~1357s remaining, 1.1 samples/s
  [100/1534] 91s elapsed, ~1302s remaining, 1.1 samples/s
  [150/1534] 140s elapsed, ~1292s remaining, 1.1 samples/s
  [200/1534] 187s elapsed, ~1249s remaining, 1.1 samples/s
  [250/1534] 236s elapsed, ~1210s remaining, 1.1 samples/s
  [300/1534] 283s elapsed, ~1166s remaining, 1.1 samples/s
  [350/1534] 331s elapsed, ~1121s remaining, 1.1 samples/s
  [400/1534] 379s elapsed, ~1074s remaining, 1.1 samples/s
  [450/1534] 427s elapsed, ~1029s remaining, 1.1 samples/s
  [500/1534] 477s elapsed, ~987s remaining, 1.0 samples/s
  [550/1534] 525s elapsed, ~939s remaining, 1.0 samples/s
  [600/1534] 573s elapsed, ~892s remaining, 1.0 samples/s
  [650/1534] 620s elapsed, ~844s remaining, 1.0 samples/s
  [700/1534] 668s elapsed, ~796s remaining, 1.0 samples/s
  [750/1534] 716s elapsed, ~749s remaining, 1.0 samples/s
  [800/1534] 764s elapsed, ~701s remaining, 1.0 samples/s
  [850/1534] 814s elapsed, ~655s remaining, 1.0 samples/s
  [900/1534] 862s elapsed, ~607s remaining, 1.0 samples/s
  [950/1534] 910s elapsed, ~560s remaining, 1.0 samples/s
  [1000/1534] 959s elapsed, ~512s remaining, 1.0 samples/s
  [1050/1534] 1008s elapsed, ~464s remaining, 1.0 samples/s
  [1100/1534] 1056s elapsed, ~417s remaining, 1.0 samples/s
  [1150/1534] 1105s elapsed, ~369s remaining, 1.0 samples/s
  [1200/1534] 1153s elapsed, ~321s remaining, 1.0 samples/s
  [1250/1534] 1202s elapsed, ~273s remaining, 1.0 samples/s
  [1300/1534] 1252s elapsed, ~225s remaining, 1.0 samples/s
  [1350/1534] 1301s elapsed, ~177s remaining, 1.0 samples/s
  [1400/1534] 1349s elapsed, ~129s remaining, 1.0 samples/s
  [1450/1534] 1398s elapsed, ~81s remaining, 1.0 samples/s
  [1500/1534] 1446s elapsed, ~33s remaining, 1.0 samples/s
  [1534/1534] 1479s elapsed, ~0s remaining, 1.0 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\text_image\test
  Accuracy:           0.8233
  Weighted Precision: 0.8539
  Weighted Recall:    0.8233
  Weighted F1:        0.8027
  Macro Precision:    0.8850
  Macro Recall:       0.7342
  Macro F1:           0.7607
  Unparseable:        0

## 6. Text+Image -- Train Set

In [7]:
# 6. Informative — text_image — train
preds, _ = run_zeroshot(
    task="informative", modality="text_image", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 9601 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_image\train.tsv
  [50/9601] 48s elapsed, ~9155s remaining, 1.0 samples/s
  [100/9601] 96s elapsed, ~9092s remaining, 1.0 samples/s
  [150/9601] 144s elapsed, ~9087s remaining, 1.0 samples/s
  [200/9601] 194s elapsed, ~9131s remaining, 1.0 samples/s
  [250/9601] 243s elapsed, ~9100s remaining, 1.0 samples/s
  [300/9601] 294s elapsed, ~9108s remaining, 1.0 samples/s
  [350/9601] 343s elapsed, ~9062s remaining, 1.0 samples/s
  [400/9601] 392s elapsed, ~9023s remaining, 1.0 samples/s
  [450/9601] 442s elapsed, ~8979s remaining, 1.0 samples/s
  [500/9601] 492s elapsed, ~8956s remaining, 1.0 samples/s
  [550/9601] 547s elapsed, ~8997s remaining, 1.0 samples/s
  [600/9601] 597s elapsed, ~8951s remaining, 1.0 samples/s
  [650/9601] 644s elapsed, ~8872s remaining, 1.0 samples/s
  [700/9601] 694s elapsed, ~8831s remaining, 1.0 samples/s
  [750/9601] 742s elapsed, ~8756s remaining, 1.0 samples/s
  [800/9601] 787s elapsed, ~8655s remaining, 1.0 samples/s
  [850/9601] 831s elapsed, ~8557s remaining, 1.0 samples/s
  [900/9601] 872s elapsed, ~8435s remaining, 1.0 samples/s
  [950/9601] 914s elapsed, ~8326s remaining, 1.0 samples/s
  [1000/9601] 956s elapsed, ~8222s remaining, 1.0 samples/s
  [1050/9601] 997s elapsed, ~8117s remaining, 1.1 samples/s
  [1100/9601] 1037s elapsed, ~8010s remaining, 1.1 samples/s
  [1150/9601] 1077s elapsed, ~7914s remaining, 1.1 samples/s
  [1200/9601] 1118s elapsed, ~7825s remaining, 1.1 samples/s
  [1250/9601] 1158s elapsed, ~7738s remaining, 1.1 samples/s
  [1300/9601] 1199s elapsed, ~7655s remaining, 1.1 samples/s
  [1350/9601] 1245s elapsed, ~7609s remaining, 1.1 samples/s
  [1400/9601] 1286s elapsed, ~7536s remaining, 1.1 samples/s
  [1450/9601] 1332s elapsed, ~7488s remaining, 1.1 samples/s
  [1500/9601] 1379s elapsed, ~7448s remaining, 1.1 samples/s
  [1550/9601] 1435s elapsed, ~7452s remaining, 1.1 samples/s
  [1600/9601] 1491s elapsed, ~7455s remaining, 1.1 samples/s
  [1650/9601] 1540s elapsed, ~7420s remaining, 1.1 samples/s
  [1700/9601] 1589s elapsed, ~7383s remaining, 1.1 samples/s
  [1750/9601] 1637s elapsed, ~7342s remaining, 1.1 samples/s
  [1800/9601] 1685s elapsed, ~7303s remaining, 1.1 samples/s
  [1850/9601] 1738s elapsed, ~7281s remaining, 1.1 samples/s
  [1900/9601] 1786s elapsed, ~7240s remaining, 1.1 samples/s
  [1950/9601] 1835s elapsed, ~7199s remaining, 1.1 samples/s
  [2000/9601] 1885s elapsed, ~7162s remaining, 1.1 samples/s
  [2050/9601] 1937s elapsed, ~7133s remaining, 1.1 samples/s
  [2100/9601] 1986s elapsed, ~7092s remaining, 1.1 samples/s
  [2150/9601] 2035s elapsed, ~7054s remaining, 1.1 samples/s
  [2200/9601] 2087s elapsed, ~7021s remaining, 1.1 samples/s
  [2250/9601] 2136s elapsed, ~6979s remaining, 1.1 samples/s
  [2300/9601] 2187s elapsed, ~6942s remaining, 1.1 samples/s
  [2350/9601] 2236s elapsed, ~6901s remaining, 1.1 samples/s
  [2400/9601] 2288s elapsed, ~6865s remaining, 1.0 samples/s
  [2450/9601] 2337s elapsed, ~6820s remaining, 1.0 samples/s
  [2500/9601] 2385s elapsed, ~6775s remaining, 1.0 samples/s
  [2550/9601] 2433s elapsed, ~6727s remaining, 1.0 samples/s
  [2600/9601] 2480s elapsed, ~6679s remaining, 1.0 samples/s
  [2650/9601] 2528s elapsed, ~6631s remaining, 1.0 samples/s
  [2700/9601] 2577s elapsed, ~6587s remaining, 1.0 samples/s
  [2750/9601] 2630s elapsed, ~6552s remaining, 1.0 samples/s
  [2800/9601] 2678s elapsed, ~6504s remaining, 1.0 samples/s
  [2850/9601] 2726s elapsed, ~6456s remaining, 1.0 samples/s
  [2900/9601] 2773s elapsed, ~6407s remaining, 1.0 samples/s
  [2950/9601] 2820s elapsed, ~6358s remaining, 1.0 samples/s
  [3000/9601] 2868s elapsed, ~6311s remaining, 1.0 samples/s
  [3050/9601] 2916s elapsed, ~6263s remaining, 1.0 samples/s
  [3100/9601] 2964s elapsed, ~6216s remaining, 1.0 samples/s
  [3150/9601] 3013s elapsed, ~6171s remaining, 1.0 samples/s
  [3200/9601] 3063s elapsed, ~6127s remaining, 1.0 samples/s
  [3250/9601] 3111s elapsed, ~6078s remaining, 1.0 samples/s
  [3300/9601] 3160s elapsed, ~6033s remaining, 1.0 samples/s
  [3350/9601] 3211s elapsed, ~5992s remaining, 1.0 samples/s
  [3400/9601] 3258s elapsed, ~5942s remaining, 1.0 samples/s
  [3450/9601] 3305s elapsed, ~5893s remaining, 1.0 samples/s
  [3500/9601] 3353s elapsed, ~5844s remaining, 1.0 samples/s
  [3550/9601] 3400s elapsed, ~5795s remaining, 1.0 samples/s
  [3600/9601] 3449s elapsed, ~5750s remaining, 1.0 samples/s
  [3650/9601] 3497s elapsed, ~5702s remaining, 1.0 samples/s
  [3700/9601] 3540s elapsed, ~5646s remaining, 1.0 samples/s
  [3750/9601] 3583s elapsed, ~5591s remaining, 1.0 samples/s
  [3800/9601] 3625s elapsed, ~5533s remaining, 1.0 samples/s
  [3850/9601] 3666s elapsed, ~5476s remaining, 1.1 samples/s
  [3900/9601] 3711s elapsed, ~5425s remaining, 1.1 samples/s
  [3950/9601] 3762s elapsed, ~5382s remaining, 1.0 samples/s
  [4000/9601] 3810s elapsed, ~5335s remaining, 1.0 samples/s
  [4050/9601] 3859s elapsed, ~5290s remaining, 1.0 samples/s
  [4100/9601] 3906s elapsed, ~5241s remaining, 1.0 samples/s
  [4150/9601] 3954s elapsed, ~5193s remaining, 1.0 samples/s
  [4200/9601] 4001s elapsed, ~5144s remaining, 1.0 samples/s
  [4250/9601] 4047s elapsed, ~5096s remaining, 1.1 samples/s
  [4300/9601] 4096s elapsed, ~5049s remaining, 1.0 samples/s
  [4350/9601] 4145s elapsed, ~5004s remaining, 1.0 samples/s
  [4400/9601] 4194s elapsed, ~4958s remaining, 1.0 samples/s
  [4450/9601] 4242s elapsed, ~4910s remaining, 1.0 samples/s
  [4500/9601] 4291s elapsed, ~4864s remaining, 1.0 samples/s
  [4550/9601] 4338s elapsed, ~4816s remaining, 1.0 samples/s
  [4600/9601] 4390s elapsed, ~4772s remaining, 1.0 samples/s
  [4650/9601] 4437s elapsed, ~4724s remaining, 1.0 samples/s
  [4700/9601] 4486s elapsed, ~4678s remaining, 1.0 samples/s
  [4750/9601] 4533s elapsed, ~4629s remaining, 1.0 samples/s
  [4800/9601] 4580s elapsed, ~4581s remaining, 1.0 samples/s
  [4850/9601] 4626s elapsed, ~4532s remaining, 1.0 samples/s
  [4900/9601] 4674s elapsed, ~4484s remaining, 1.0 samples/s
  [4950/9601] 4723s elapsed, ~4437s remaining, 1.0 samples/s
  [5000/9601] 4773s elapsed, ~4392s remaining, 1.0 samples/s
  [5050/9601] 4820s elapsed, ~4344s remaining, 1.0 samples/s
  [5100/9601] 4870s elapsed, ~4298s remaining, 1.0 samples/s
  [5150/9601] 4917s elapsed, ~4249s remaining, 1.0 samples/s
  [5200/9601] 4967s elapsed, ~4204s remaining, 1.0 samples/s
  [5250/9601] 5014s elapsed, ~4155s remaining, 1.0 samples/s
  [5300/9601] 5066s elapsed, ~4111s remaining, 1.0 samples/s
  [5350/9601] 5116s elapsed, ~4065s remaining, 1.0 samples/s
  [5400/9601] 5166s elapsed, ~4019s remaining, 1.0 samples/s
  [5450/9601] 5213s elapsed, ~3970s remaining, 1.0 samples/s
  [5500/9601] 5260s elapsed, ~3922s remaining, 1.0 samples/s
  [5550/9601] 5307s elapsed, ~3874s remaining, 1.0 samples/s
  [5600/9601] 5354s elapsed, ~3825s remaining, 1.0 samples/s
  [5650/9601] 5402s elapsed, ~3777s remaining, 1.0 samples/s
  [5700/9601] 5449s elapsed, ~3729s remaining, 1.0 samples/s
  [5750/9601] 5496s elapsed, ~3681s remaining, 1.0 samples/s
  [5800/9601] 5545s elapsed, ~3634s remaining, 1.0 samples/s
  [5850/9601] 5592s elapsed, ~3586s remaining, 1.0 samples/s
  [5900/9601] 5639s elapsed, ~3537s remaining, 1.0 samples/s
  [5950/9601] 5689s elapsed, ~3491s remaining, 1.0 samples/s
  [6000/9601] 5735s elapsed, ~3442s remaining, 1.0 samples/s
  [6050/9601] 5782s elapsed, ~3394s remaining, 1.0 samples/s
  [6100/9601] 5832s elapsed, ~3347s remaining, 1.0 samples/s
  [6150/9601] 5875s elapsed, ~3297s remaining, 1.0 samples/s
  [6200/9601] 5920s elapsed, ~3248s remaining, 1.0 samples/s
  [6250/9601] 5964s elapsed, ~3198s remaining, 1.0 samples/s
  [6300/9601] 6004s elapsed, ~3146s remaining, 1.0 samples/s
  [6350/9601] 6044s elapsed, ~3094s remaining, 1.1 samples/s
  [6400/9601] 6083s elapsed, ~3042s remaining, 1.1 samples/s
  [6450/9601] 6122s elapsed, ~2991s remaining, 1.1 samples/s
  [6500/9601] 6161s elapsed, ~2939s remaining, 1.1 samples/s
  [6550/9601] 6200s elapsed, ~2888s remaining, 1.1 samples/s
  [6600/9601] 6238s elapsed, ~2836s remaining, 1.1 samples/s
  [6650/9601] 6276s elapsed, ~2785s remaining, 1.1 samples/s
  [6700/9601] 6315s elapsed, ~2734s remaining, 1.1 samples/s
  [6750/9601] 6354s elapsed, ~2684s remaining, 1.1 samples/s
  [6800/9601] 6391s elapsed, ~2632s remaining, 1.1 samples/s
  [6850/9601] 6430s elapsed, ~2582s remaining, 1.1 samples/s
  [6900/9601] 6467s elapsed, ~2531s remaining, 1.1 samples/s
  [6950/9601] 6504s elapsed, ~2481s remaining, 1.1 samples/s
  [7000/9601] 6545s elapsed, ~2432s remaining, 1.1 samples/s
  [7050/9601] 6583s elapsed, ~2382s remaining, 1.1 samples/s
  [7100/9601] 6620s elapsed, ~2332s remaining, 1.1 samples/s
  [7150/9601] 6658s elapsed, ~2282s remaining, 1.1 samples/s
  [7200/9601] 6696s elapsed, ~2233s remaining, 1.1 samples/s
  [7250/9601] 6733s elapsed, ~2183s remaining, 1.1 samples/s
  [7300/9601] 6772s elapsed, ~2135s remaining, 1.1 samples/s
  [7350/9601] 6810s elapsed, ~2086s remaining, 1.1 samples/s
  [7400/9601] 6847s elapsed, ~2037s remaining, 1.1 samples/s
  [7450/9601] 6885s elapsed, ~1988s remaining, 1.1 samples/s
  [7500/9601] 6923s elapsed, ~1940s remaining, 1.1 samples/s
  [7550/9601] 6961s elapsed, ~1891s remaining, 1.1 samples/s
  [7600/9601] 7000s elapsed, ~1843s remaining, 1.1 samples/s
  [7650/9601] 7038s elapsed, ~1795s remaining, 1.1 samples/s
  [7700/9601] 7076s elapsed, ~1747s remaining, 1.1 samples/s
  [7750/9601] 7114s elapsed, ~1699s remaining, 1.1 samples/s
  [7800/9601] 7151s elapsed, ~1651s remaining, 1.1 samples/s
  [7850/9601] 7189s elapsed, ~1604s remaining, 1.1 samples/s
  [7900/9601] 7227s elapsed, ~1556s remaining, 1.1 samples/s
  [7950/9601] 7267s elapsed, ~1509s remaining, 1.1 samples/s
  [8000/9601] 7307s elapsed, ~1462s remaining, 1.1 samples/s
  [8050/9601] 7344s elapsed, ~1415s remaining, 1.1 samples/s
  [8100/9601] 7382s elapsed, ~1368s remaining, 1.1 samples/s
  [8150/9601] 7420s elapsed, ~1321s remaining, 1.1 samples/s
  [8200/9601] 7458s elapsed, ~1274s remaining, 1.1 samples/s
  [8250/9601] 7496s elapsed, ~1227s remaining, 1.1 samples/s
  [8300/9601] 7534s elapsed, ~1181s remaining, 1.1 samples/s
  [8350/9601] 7573s elapsed, ~1135s remaining, 1.1 samples/s
  [8400/9601] 7611s elapsed, ~1088s remaining, 1.1 samples/s
  [8450/9601] 7648s elapsed, ~1042s remaining, 1.1 samples/s
  [8500/9601] 7686s elapsed, ~996s remaining, 1.1 samples/s
  [8550/9601] 7725s elapsed, ~950s remaining, 1.1 samples/s
  [8600/9601] 7761s elapsed, ~903s remaining, 1.1 samples/s
  [8650/9601] 7798s elapsed, ~857s remaining, 1.1 samples/s
  [8700/9601] 7835s elapsed, ~811s remaining, 1.1 samples/s
  [8750/9601] 7872s elapsed, ~766s remaining, 1.1 samples/s
  [8800/9601] 7911s elapsed, ~720s remaining, 1.1 samples/s
  [8850/9601] 7948s elapsed, ~674s remaining, 1.1 samples/s
  [8900/9601] 7985s elapsed, ~629s remaining, 1.1 samples/s
  [8950/9601] 8023s elapsed, ~584s remaining, 1.1 samples/s
  [9000/9601] 8060s elapsed, ~538s remaining, 1.1 samples/s
  [9050/9601] 8098s elapsed, ~493s remaining, 1.1 samples/s
  [9100/9601] 8135s elapsed, ~448s remaining, 1.1 samples/s
  [9150/9601] 8170s elapsed, ~403s remaining, 1.1 samples/s
  [9200/9601] 8206s elapsed, ~358s remaining, 1.1 samples/s
  [9250/9601] 8243s elapsed, ~313s remaining, 1.1 samples/s
  [9300/9601] 8279s elapsed, ~268s remaining, 1.1 samples/s
  [9350/9601] 8316s elapsed, ~223s remaining, 1.1 samples/s
  [9400/9601] 8353s elapsed, ~179s remaining, 1.1 samples/s
  [9450/9601] 8391s elapsed, ~134s remaining, 1.1 samples/s
  [9500/9601] 8427s elapsed, ~90s remaining, 1.1 samples/s
  [9550/9601] 8463s elapsed, ~45s remaining, 1.1 samples/s
  [9600/9601] 8500s elapsed, ~1s remaining, 1.1 samples/s
  [9601/9601] 8501s elapsed, ~0s remaining, 1.1 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\informative\text_image\train
  Accuracy:           0.8248
  Weighted Precision: 0.8519
  Weighted Recall:    0.8248
  Weighted F1:        0.8069
  Macro Precision:    0.8788
  Macro Recall:       0.7465
  Macro F1:           0.7713
  Unparseable:        0

### Informative Summary

In [8]:
show_summary("informative")

Task: informative
Model: llama-3.2-11b

     Modality  Split  Samples Accuracy Weighted F1 Macro F1  Unparseable
0   text_only   test     1534   0.8357      0.8311   0.8041            0
1   text_only  train     8293   0.8184      0.8141   0.7860            0
2  image_only   test     1534   0.8605      0.8546   0.8297            0
3  image_only  train     9601   0.8591      0.8537   0.8320            0
4  text_image   test     1534   0.8233      0.8027   0.7607            0
5  text_image  train     9601   0.8248      0.8069   0.7713            0

## Humanitarian Task (6 experiments)

## 1. Text-Only -- Test Set

In [2]:
# 7. Humanitarian — text_only — test
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_only\test.tsv
  [50/955] 11s elapsed, ~198s remaining, 4.6 samples/s
  [100/955] 21s elapsed, ~180s remaining, 4.8 samples/s
  [150/955] 31s elapsed, ~167s remaining, 4.8 samples/s
  [200/955] 41s elapsed, ~155s remaining, 4.9 samples/s
  [250/955] 51s elapsed, ~145s remaining, 4.9 samples/s
  [300/955] 61s elapsed, ~134s remaining, 4.9 samples/s
  [350/955] 71s elapsed, ~124s remaining, 4.9 samples/s
  [400/955] 81s elapsed, ~113s remaining, 4.9 samples/s
  [450/955] 91s elapsed, ~103s remaining, 4.9 samples/s
  [500/955] 101s elapsed, ~92s remaining, 4.9 samples/s
  [550/955] 111s elapsed, ~82s remaining, 5.0 samples/s
  [600/955] 121s elapsed, ~71s remaining, 5.0 samples/s
  [650/955] 131s elapsed, ~61s remaining, 5.0 samples/s
  [700/955] 141s elapsed, ~51s remaining, 5.0 samples/s
  [750/955] 151s elapsed, ~41s remaining, 5.0 samples/s
  [800/955] 160s elapsed, ~31s remaining, 5.0 samples/s
  [850/955] 170s elapsed, ~21s remaining, 5.0 samples/s
  [900/955] 180s elapsed, ~11s remaining, 5.0 samples/s
  [950/955] 190s elapsed, ~1s remaining, 5.0 samples/s
  [955/955] 191s elapsed, ~0s remaining, 5.0 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\text_only\test
  Accuracy:           0.7414
  Weighted Precision: 0.7836
  Weighted Recall:    0.7414
  Weighted F1:        0.7382
  Macro Precision:    0.7097
  Macro Recall:       0.6708
  Macro F1:           0.6343
  Unparseable:        0

## 2. Text-Only -- Train Set

In [3]:
# 8. Humanitarian — text_only — train
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 5263 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_only\train.tsv
  [50/5263] 10s elapsed, ~1021s remaining, 5.1 samples/s
  [100/5263] 20s elapsed, ~1020s remaining, 5.1 samples/s
  [150/5263] 30s elapsed, ~1014s remaining, 5.0 samples/s
  [200/5263] 40s elapsed, ~1001s remaining, 5.1 samples/s
  [250/5263] 49s elapsed, ~993s remaining, 5.1 samples/s
  [300/5263] 59s elapsed, ~978s remaining, 5.1 samples/s
  [350/5263] 69s elapsed, ~965s remaining, 5.1 samples/s
  [400/5263] 79s elapsed, ~959s remaining, 5.1 samples/s
  [450/5263] 89s elapsed, ~953s remaining, 5.0 samples/s
  [500/5263] 99s elapsed, ~947s remaining, 5.0 samples/s
  [550/5263] 110s elapsed, ~941s remaining, 5.0 samples/s
  [600/5263] 120s elapsed, ~934s remaining, 5.0 samples/s
  [650/5263] 131s elapsed, ~931s remaining, 5.0 samples/s
  [700/5263] 142s elapsed, ~928s remaining, 4.9 samples/s
  [750/5263] 153s elapsed, ~922s remaining, 4.9 samples/s
  [800/5263] 164s elapsed, ~916s remaining, 4.9 samples/s
  [850/5263] 175s elapsed, ~910s remaining, 4.9 samples/s
  [900/5263] 186s elapsed, ~903s remaining, 4.8 samples/s
  [950/5263] 197s elapsed, ~895s remaining, 4.8 samples/s
  [1000/5263] 208s elapsed, ~887s remaining, 4.8 samples/s
  [1050/5263] 219s elapsed, ~878s remaining, 4.8 samples/s
  [1100/5263] 230s elapsed, ~870s remaining, 4.8 samples/s
  [1150/5263] 241s elapsed, ~862s remaining, 4.8 samples/s
  [1200/5263] 252s elapsed, ~853s remaining, 4.8 samples/s
  [1250/5263] 263s elapsed, ~844s remaining, 4.8 samples/s
  [1300/5263] 274s elapsed, ~834s remaining, 4.8 samples/s
  [1350/5263] 284s elapsed, ~824s remaining, 4.8 samples/s
  [1400/5263] 295s elapsed, ~814s remaining, 4.7 samples/s
  [1450/5263] 306s elapsed, ~804s remaining, 4.7 samples/s
  [1500/5263] 316s elapsed, ~794s remaining, 4.7 samples/s
  [1550/5263] 327s elapsed, ~784s remaining, 4.7 samples/s
  [1600/5263] 338s elapsed, ~774s remaining, 4.7 samples/s
  [1650/5263] 349s elapsed, ~764s remaining, 4.7 samples/s
  [1700/5263] 360s elapsed, ~754s remaining, 4.7 samples/s
  [1750/5263] 371s elapsed, ~744s remaining, 4.7 samples/s
  [1800/5263] 382s elapsed, ~734s remaining, 4.7 samples/s
  [1850/5263] 393s elapsed, ~724s remaining, 4.7 samples/s
  [1900/5263] 403s elapsed, ~714s remaining, 4.7 samples/s
  [1950/5263] 414s elapsed, ~704s remaining, 4.7 samples/s
  [2000/5263] 425s elapsed, ~694s remaining, 4.7 samples/s
  [2050/5263] 436s elapsed, ~684s remaining, 4.7 samples/s
  [2100/5263] 447s elapsed, ~673s remaining, 4.7 samples/s
  [2150/5263] 458s elapsed, ~663s remaining, 4.7 samples/s
  [2200/5263] 469s elapsed, ~653s remaining, 4.7 samples/s
  [2250/5263] 480s elapsed, ~642s remaining, 4.7 samples/s
  [2300/5263] 490s elapsed, ~632s remaining, 4.7 samples/s
  [2350/5263] 501s elapsed, ~621s remaining, 4.7 samples/s
  [2400/5263] 512s elapsed, ~611s remaining, 4.7 samples/s
  [2450/5263] 522s elapsed, ~600s remaining, 4.7 samples/s
  [2500/5263] 533s elapsed, ~589s remaining, 4.7 samples/s
  [2550/5263] 543s elapsed, ~578s remaining, 4.7 samples/s
  [2600/5263] 554s elapsed, ~567s remaining, 4.7 samples/s
  [2650/5263] 564s elapsed, ~556s remaining, 4.7 samples/s
  [2700/5263] 574s elapsed, ~545s remaining, 4.7 samples/s
  [2750/5263] 585s elapsed, ~534s remaining, 4.7 samples/s
  [2800/5263] 595s elapsed, ~524s remaining, 4.7 samples/s
  [2850/5263] 606s elapsed, ~513s remaining, 4.7 samples/s
  [2900/5263] 616s elapsed, ~502s remaining, 4.7 samples/s
  [2950/5263] 626s elapsed, ~491s remaining, 4.7 samples/s
  [3000/5263] 636s elapsed, ~480s remaining, 4.7 samples/s
  [3050/5263] 647s elapsed, ~469s remaining, 4.7 samples/s
  [3100/5263] 657s elapsed, ~458s remaining, 4.7 samples/s
  [3150/5263] 667s elapsed, ~448s remaining, 4.7 samples/s
  [3200/5263] 678s elapsed, ~437s remaining, 4.7 samples/s
  [3250/5263] 688s elapsed, ~426s remaining, 4.7 samples/s
  [3300/5263] 698s elapsed, ~415s remaining, 4.7 samples/s
  [3350/5263] 708s elapsed, ~404s remaining, 4.7 samples/s
  [3400/5263] 719s elapsed, ~394s remaining, 4.7 samples/s
  [3450/5263] 729s elapsed, ~383s remaining, 4.7 samples/s
  [3500/5263] 739s elapsed, ~372s remaining, 4.7 samples/s
  [3550/5263] 750s elapsed, ~362s remaining, 4.7 samples/s
  [3600/5263] 760s elapsed, ~351s remaining, 4.7 samples/s
  [3650/5263] 771s elapsed, ~341s remaining, 4.7 samples/s
  [3700/5263] 781s elapsed, ~330s remaining, 4.7 samples/s
  [3750/5263] 792s elapsed, ~320s remaining, 4.7 samples/s
  [3800/5263] 803s elapsed, ~309s remaining, 4.7 samples/s
  [3850/5263] 814s elapsed, ~299s remaining, 4.7 samples/s
  [3900/5263] 825s elapsed, ~288s remaining, 4.7 samples/s
  [3950/5263] 836s elapsed, ~278s remaining, 4.7 samples/s
  [4000/5263] 847s elapsed, ~267s remaining, 4.7 samples/s
  [4050/5263] 858s elapsed, ~257s remaining, 4.7 samples/s
  [4100/5263] 869s elapsed, ~246s remaining, 4.7 samples/s
  [4150/5263] 880s elapsed, ~236s remaining, 4.7 samples/s
  [4200/5263] 891s elapsed, ~225s remaining, 4.7 samples/s
  [4250/5263] 902s elapsed, ~215s remaining, 4.7 samples/s
  [4300/5263] 913s elapsed, ~204s remaining, 4.7 samples/s
  [4350/5263] 923s elapsed, ~194s remaining, 4.7 samples/s
  [4400/5263] 935s elapsed, ~183s remaining, 4.7 samples/s
  [4450/5263] 945s elapsed, ~173s remaining, 4.7 samples/s
  [4500/5263] 956s elapsed, ~162s remaining, 4.7 samples/s
  [4550/5263] 967s elapsed, ~152s remaining, 4.7 samples/s
  [4600/5263] 978s elapsed, ~141s remaining, 4.7 samples/s
  [4650/5263] 989s elapsed, ~130s remaining, 4.7 samples/s
  [4700/5263] 1000s elapsed, ~120s remaining, 4.7 samples/s
  [4750/5263] 1011s elapsed, ~109s remaining, 4.7 samples/s
  [4800/5263] 1022s elapsed, ~99s remaining, 4.7 samples/s
  [4850/5263] 1033s elapsed, ~88s remaining, 4.7 samples/s
  [4900/5263] 1044s elapsed, ~77s remaining, 4.7 samples/s
  [4950/5263] 1055s elapsed, ~67s remaining, 4.7 samples/s
  [5000/5263] 1066s elapsed, ~56s remaining, 4.7 samples/s
  [5050/5263] 1077s elapsed, ~45s remaining, 4.7 samples/s
  [5100/5263] 1088s elapsed, ~35s remaining, 4.7 samples/s
  [5150/5263] 1099s elapsed, ~24s remaining, 4.7 samples/s
  [5200/5263] 1110s elapsed, ~13s remaining, 4.7 samples/s
  [5250/5263] 1120s elapsed, ~3s remaining, 4.7 samples/s
  [5263/5263] 1123s elapsed, ~0s remaining, 4.7 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\text_only\train
  Accuracy:           0.7372
  Weighted Precision: 0.7836
  Weighted Recall:    0.7372
  Weighted F1:        0.7324
  Macro Precision:    0.7049
  Macro Recall:       0.6318
  Macro F1:           0.6165
  Unparseable:        0

## 3. Image-Only -- Test Set

In [4]:
# 9. Humanitarian — image_only — test
preds, _ = run_zeroshot(
    task="humanitarian", modality="image_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\image_only\test.tsv
  [50/955] 41s elapsed, ~735s remaining, 1.2 samples/s
  [100/955] 80s elapsed, ~687s remaining, 1.2 samples/s
  [150/955] 121s elapsed, ~652s remaining, 1.2 samples/s
  [200/955] 161s elapsed, ~609s remaining, 1.2 samples/s
  [250/955] 201s elapsed, ~567s remaining, 1.2 samples/s
  [300/955] 241s elapsed, ~527s remaining, 1.2 samples/s
  [350/955] 282s elapsed, ~487s remaining, 1.2 samples/s
  [400/955] 321s elapsed, ~446s remaining, 1.2 samples/s
  [450/955] 363s elapsed, ~407s remaining, 1.2 samples/s
  [500/955] 404s elapsed, ~367s remaining, 1.2 samples/s
  [550/955] 445s elapsed, ~327s remaining, 1.2 samples/s
  [600/955] 485s elapsed, ~287s remaining, 1.2 samples/s
  [650/955] 526s elapsed, ~247s remaining, 1.2 samples/s
  [700/955] 567s elapsed, ~207s remaining, 1.2 samples/s
  [750/955] 609s elapsed, ~167s remaining, 1.2 samples/s
  [800/955] 650s elapsed, ~126s remaining, 1.2 samples/s
  [850/955] 691s elapsed, ~85s remaining, 1.2 samples/s
  [900/955] 732s elapsed, ~45s remaining, 1.2 samples/s
  [950/955] 772s elapsed, ~4s remaining, 1.2 samples/s
  [955/955] 776s elapsed, ~0s remaining, 1.2 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\image_only\test
  Accuracy:           0.7654
  Weighted Precision: 0.7717
  Weighted Recall:    0.7654
  Weighted F1:        0.7571
  Macro Precision:    0.6650
  Macro Recall:       0.6256
  Macro F1:           0.6275
  Unparseable:        0

## 4. Image-Only -- Train Set

In [5]:
# 10. Humanitarian — image_only — train
preds, _ = run_zeroshot(
    task="humanitarian", modality="image_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 6126 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\image_only\train.tsv
  [50/6126] 40s elapsed, ~4914s remaining, 1.2 samples/s
  [100/6126] 81s elapsed, ~4864s remaining, 1.2 samples/s
  [150/6126] 121s elapsed, ~4824s remaining, 1.2 samples/s
  [200/6126] 161s elapsed, ~4768s remaining, 1.2 samples/s
  [250/6126] 202s elapsed, ~4751s remaining, 1.2 samples/s
  [300/6126] 243s elapsed, ~4725s remaining, 1.2 samples/s
  [350/6126] 284s elapsed, ~4694s remaining, 1.2 samples/s
  [400/6126] 325s elapsed, ~4659s remaining, 1.2 samples/s
  [450/6126] 367s elapsed, ~4625s remaining, 1.2 samples/s
  [500/6126] 408s elapsed, ~4592s remaining, 1.2 samples/s
  [550/6126] 449s elapsed, ~4557s remaining, 1.2 samples/s
  [600/6126] 491s elapsed, ~4522s remaining, 1.2 samples/s
  [650/6126] 533s elapsed, ~4493s remaining, 1.2 samples/s
  [700/6126] 575s elapsed, ~4456s remaining, 1.2 samples/s
  [750/6126] 616s elapsed, ~4417s remaining, 1.2 samples/s
  [800/6126] 657s elapsed, ~4375s remaining, 1.2 samples/s
  [850/6126] 697s elapsed, ~4329s remaining, 1.2 samples/s
  [900/6126] 738s elapsed, ~4285s remaining, 1.2 samples/s
  [950/6126] 778s elapsed, ~4240s remaining, 1.2 samples/s
  [1000/6126] 819s elapsed, ~4198s remaining, 1.2 samples/s
  [1050/6126] 860s elapsed, ~4158s remaining, 1.2 samples/s
  [1100/6126] 902s elapsed, ~4121s remaining, 1.2 samples/s
  [1150/6126] 943s elapsed, ~4082s remaining, 1.2 samples/s
  [1200/6126] 985s elapsed, ~4045s remaining, 1.2 samples/s
  [1250/6126] 1027s elapsed, ~4005s remaining, 1.2 samples/s
  [1300/6126] 1068s elapsed, ~3966s remaining, 1.2 samples/s
  [1350/6126] 1110s elapsed, ~3926s remaining, 1.2 samples/s
  [1400/6126] 1151s elapsed, ~3887s remaining, 1.2 samples/s
  [1450/6126] 1193s elapsed, ~3847s remaining, 1.2 samples/s
  [1500/6126] 1233s elapsed, ~3803s remaining, 1.2 samples/s
  [1550/6126] 1274s elapsed, ~3761s remaining, 1.2 samples/s
  [1600/6126] 1314s elapsed, ~3718s remaining, 1.2 samples/s
  [1650/6126] 1355s elapsed, ~3676s remaining, 1.2 samples/s
  [1700/6126] 1395s elapsed, ~3632s remaining, 1.2 samples/s
  [1750/6126] 1436s elapsed, ~3591s remaining, 1.2 samples/s
  [1800/6126] 1476s elapsed, ~3547s remaining, 1.2 samples/s
  [1850/6126] 1517s elapsed, ~3506s remaining, 1.2 samples/s
  [1900/6126] 1558s elapsed, ~3465s remaining, 1.2 samples/s
  [1950/6126] 1599s elapsed, ~3424s remaining, 1.2 samples/s
  [2000/6126] 1639s elapsed, ~3382s remaining, 1.2 samples/s
  [2050/6126] 1682s elapsed, ~3344s remaining, 1.2 samples/s
  [2100/6126] 1723s elapsed, ~3303s remaining, 1.2 samples/s
  [2150/6126] 1764s elapsed, ~3262s remaining, 1.2 samples/s
  [2200/6126] 1805s elapsed, ~3221s remaining, 1.2 samples/s
  [2250/6126] 1845s elapsed, ~3179s remaining, 1.2 samples/s
  [2300/6126] 1886s elapsed, ~3138s remaining, 1.2 samples/s
  [2350/6126] 1927s elapsed, ~3097s remaining, 1.2 samples/s
  [2400/6126] 1968s elapsed, ~3056s remaining, 1.2 samples/s
  [2450/6126] 2008s elapsed, ~3013s remaining, 1.2 samples/s
  [2500/6126] 2048s elapsed, ~2970s remaining, 1.2 samples/s
  [2550/6126] 2087s elapsed, ~2927s remaining, 1.2 samples/s
  [2600/6126] 2128s elapsed, ~2885s remaining, 1.2 samples/s
  [2650/6126] 2168s elapsed, ~2844s remaining, 1.2 samples/s
  [2700/6126] 2209s elapsed, ~2803s remaining, 1.2 samples/s
  [2750/6126] 2251s elapsed, ~2763s remaining, 1.2 samples/s
  [2800/6126] 2292s elapsed, ~2722s remaining, 1.2 samples/s
  [2850/6126] 2333s elapsed, ~2681s remaining, 1.2 samples/s
  [2900/6126] 2374s elapsed, ~2641s remaining, 1.2 samples/s
  [2950/6126] 2415s elapsed, ~2600s remaining, 1.2 samples/s
  [3000/6126] 2456s elapsed, ~2559s remaining, 1.2 samples/s
  [3050/6126] 2497s elapsed, ~2518s remaining, 1.2 samples/s
  [3100/6126] 2537s elapsed, ~2477s remaining, 1.2 samples/s
  [3150/6126] 2578s elapsed, ~2435s remaining, 1.2 samples/s
  [3200/6126] 2618s elapsed, ~2394s remaining, 1.2 samples/s
  [3250/6126] 2658s elapsed, ~2352s remaining, 1.2 samples/s
  [3300/6126] 2698s elapsed, ~2310s remaining, 1.2 samples/s
  [3350/6126] 2738s elapsed, ~2268s remaining, 1.2 samples/s
  [3400/6126] 2778s elapsed, ~2227s remaining, 1.2 samples/s
  [3450/6126] 2819s elapsed, ~2187s remaining, 1.2 samples/s
  [3500/6126] 2860s elapsed, ~2145s remaining, 1.2 samples/s
  [3550/6126] 2901s elapsed, ~2105s remaining, 1.2 samples/s
  [3600/6126] 2941s elapsed, ~2064s remaining, 1.2 samples/s
  [3650/6126] 2982s elapsed, ~2023s remaining, 1.2 samples/s
  [3700/6126] 3022s elapsed, ~1982s remaining, 1.2 samples/s
  [3750/6126] 3063s elapsed, ~1941s remaining, 1.2 samples/s
  [3800/6126] 3104s elapsed, ~1900s remaining, 1.2 samples/s
  [3850/6126] 3145s elapsed, ~1859s remaining, 1.2 samples/s
  [3900/6126] 3185s elapsed, ~1818s remaining, 1.2 samples/s
  [3950/6126] 3225s elapsed, ~1777s remaining, 1.2 samples/s
  [4000/6126] 3265s elapsed, ~1735s remaining, 1.2 samples/s
  [4050/6126] 3305s elapsed, ~1694s remaining, 1.2 samples/s
  [4100/6126] 3345s elapsed, ~1653s remaining, 1.2 samples/s
  [4150/6126] 3385s elapsed, ~1612s remaining, 1.2 samples/s
  [4200/6126] 3425s elapsed, ~1571s remaining, 1.2 samples/s
  [4250/6126] 3466s elapsed, ~1530s remaining, 1.2 samples/s
  [4300/6126] 3507s elapsed, ~1489s remaining, 1.2 samples/s
  [4350/6126] 3548s elapsed, ~1448s remaining, 1.2 samples/s
  [4400/6126] 3589s elapsed, ~1408s remaining, 1.2 samples/s
  [4450/6126] 3630s elapsed, ~1367s remaining, 1.2 samples/s
  [4500/6126] 3671s elapsed, ~1326s remaining, 1.2 samples/s
  [4550/6126] 3712s elapsed, ~1286s remaining, 1.2 samples/s
  [4600/6126] 3752s elapsed, ~1245s remaining, 1.2 samples/s
  [4650/6126] 3794s elapsed, ~1204s remaining, 1.2 samples/s
  [4700/6126] 3834s elapsed, ~1163s remaining, 1.2 samples/s
  [4750/6126] 3874s elapsed, ~1122s remaining, 1.2 samples/s
  [4800/6126] 3915s elapsed, ~1082s remaining, 1.2 samples/s
  [4850/6126] 3955s elapsed, ~1041s remaining, 1.2 samples/s
  [4900/6126] 3995s elapsed, ~1000s remaining, 1.2 samples/s
  [4950/6126] 4035s elapsed, ~959s remaining, 1.2 samples/s
  [5000/6126] 4075s elapsed, ~918s remaining, 1.2 samples/s
  [5050/6126] 4116s elapsed, ~877s remaining, 1.2 samples/s
  [5100/6126] 4156s elapsed, ~836s remaining, 1.2 samples/s
  [5150/6126] 4197s elapsed, ~795s remaining, 1.2 samples/s
  [5200/6126] 4238s elapsed, ~755s remaining, 1.2 samples/s
  [5250/6126] 4279s elapsed, ~714s remaining, 1.2 samples/s
  [5300/6126] 4320s elapsed, ~673s remaining, 1.2 samples/s
  [5350/6126] 4360s elapsed, ~632s remaining, 1.2 samples/s
  [5400/6126] 4401s elapsed, ~592s remaining, 1.2 samples/s
  [5450/6126] 4442s elapsed, ~551s remaining, 1.2 samples/s
  [5500/6126] 4482s elapsed, ~510s remaining, 1.2 samples/s
  [5550/6126] 4522s elapsed, ~469s remaining, 1.2 samples/s
  [5600/6126] 4562s elapsed, ~429s remaining, 1.2 samples/s
  [5650/6126] 4602s elapsed, ~388s remaining, 1.2 samples/s
  [5700/6126] 4642s elapsed, ~347s remaining, 1.2 samples/s
  [5750/6126] 4682s elapsed, ~306s remaining, 1.2 samples/s
  [5800/6126] 4722s elapsed, ~265s remaining, 1.2 samples/s
  [5850/6126] 4762s elapsed, ~225s remaining, 1.2 samples/s
  [5900/6126] 4804s elapsed, ~184s remaining, 1.2 samples/s
  [5950/6126] 4846s elapsed, ~143s remaining, 1.2 samples/s
  [6000/6126] 4887s elapsed, ~103s remaining, 1.2 samples/s
  [6050/6126] 4929s elapsed, ~62s remaining, 1.2 samples/s
  [6100/6126] 4970s elapsed, ~21s remaining, 1.2 samples/s
  [6126/6126] 4992s elapsed, ~0s remaining, 1.2 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\image_only\train
  Accuracy:           0.7729
  Weighted Precision: 0.7759
  Weighted Recall:    0.7729
  Weighted F1:        0.7679
  Macro Precision:    0.6868
  Macro Recall:       0.6775
  Macro F1:           0.6694
  Unparseable:        0

## 5. Text+Image -- Test Set

In [6]:
# 11. Humanitarian — text_image — test
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_image", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_image\test.tsv
  [50/955] 41s elapsed, ~743s remaining, 1.2 samples/s
  [100/955] 82s elapsed, ~703s remaining, 1.2 samples/s
  [150/955] 125s elapsed, ~672s remaining, 1.2 samples/s
  [200/955] 167s elapsed, ~629s remaining, 1.2 samples/s
  [250/955] 207s elapsed, ~585s remaining, 1.2 samples/s
  [300/955] 249s elapsed, ~543s remaining, 1.2 samples/s
  [350/955] 290s elapsed, ~501s remaining, 1.2 samples/s
  [400/955] 330s elapsed, ~458s remaining, 1.2 samples/s
  [450/955] 373s elapsed, ~418s remaining, 1.2 samples/s
  [500/955] 413s elapsed, ~376s remaining, 1.2 samples/s
  [550/955] 455s elapsed, ~335s remaining, 1.2 samples/s
  [600/955] 496s elapsed, ~294s remaining, 1.2 samples/s
  [650/955] 539s elapsed, ~253s remaining, 1.2 samples/s
  [700/955] 581s elapsed, ~212s remaining, 1.2 samples/s
  [750/955] 625s elapsed, ~171s remaining, 1.2 samples/s
  [800/955] 666s elapsed, ~129s remaining, 1.2 samples/s
  [850/955] 707s elapsed, ~87s remaining, 1.2 samples/s
  [900/955] 748s elapsed, ~46s remaining, 1.2 samples/s
  [950/955] 790s elapsed, ~4s remaining, 1.2 samples/s
  [955/955] 794s elapsed, ~0s remaining, 1.2 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\text_image\test
  Accuracy:           0.7424
  Weighted Precision: 0.7607
  Weighted Recall:    0.7424
  Weighted F1:        0.7360
  Macro Precision:    0.6783
  Macro Recall:       0.5856
  Macro F1:           0.5947
  Unparseable:        0

## 6. Text+Image -- Train Set

In [7]:
# 12. Humanitarian — text_image — train
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_image", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 6126 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_image\train.tsv
  [50/6126] 41s elapsed, ~5013s remaining, 1.2 samples/s
  [100/6126] 83s elapsed, ~5011s remaining, 1.2 samples/s
  [150/6126] 124s elapsed, ~4943s remaining, 1.2 samples/s
  [200/6126] 164s elapsed, ~4866s remaining, 1.2 samples/s
  [250/6126] 206s elapsed, ~4832s remaining, 1.2 samples/s
  [300/6126] 247s elapsed, ~4788s remaining, 1.2 samples/s
  [350/6126] 287s elapsed, ~4742s remaining, 1.2 samples/s
  [400/6126] 329s elapsed, ~4709s remaining, 1.2 samples/s
  [450/6126] 372s elapsed, ~4690s remaining, 1.2 samples/s
  [500/6126] 414s elapsed, ~4655s remaining, 1.2 samples/s
  [550/6126] 456s elapsed, ~4618s remaining, 1.2 samples/s
  [600/6126] 498s elapsed, ~4582s remaining, 1.2 samples/s
  [650/6126] 541s elapsed, ~4557s remaining, 1.2 samples/s
  [700/6126] 583s elapsed, ~4520s remaining, 1.2 samples/s
  [750/6126] 625s elapsed, ~4480s remaining, 1.2 samples/s
  [800/6126] 667s elapsed, ~4439s remaining, 1.2 samples/s
  [850/6126] 709s elapsed, ~4398s remaining, 1.2 samples/s
  [900/6126] 751s elapsed, ~4362s remaining, 1.2 samples/s
  [950/6126] 792s elapsed, ~4316s remaining, 1.2 samples/s
  [1000/6126] 833s elapsed, ~4269s remaining, 1.2 samples/s
  [1050/6126] 874s elapsed, ~4224s remaining, 1.2 samples/s
  [1100/6126] 915s elapsed, ~4179s remaining, 1.2 samples/s
  [1150/6126] 956s elapsed, ~4137s remaining, 1.2 samples/s
  [1200/6126] 998s elapsed, ~4096s remaining, 1.2 samples/s
  [1250/6126] 1039s elapsed, ~4055s remaining, 1.2 samples/s
  [1300/6126] 1083s elapsed, ~4020s remaining, 1.2 samples/s
  [1350/6126] 1125s elapsed, ~3980s remaining, 1.2 samples/s
  [1400/6126] 1167s elapsed, ~3940s remaining, 1.2 samples/s
  [1450/6126] 1210s elapsed, ~3901s remaining, 1.2 samples/s
  [1500/6126] 1252s elapsed, ~3860s remaining, 1.2 samples/s
  [1550/6126] 1294s elapsed, ~3820s remaining, 1.2 samples/s
  [1600/6126] 1336s elapsed, ~3779s remaining, 1.2 samples/s
  [1650/6126] 1379s elapsed, ~3740s remaining, 1.2 samples/s
  [1700/6126] 1419s elapsed, ~3696s remaining, 1.2 samples/s
  [1750/6126] 1462s elapsed, ~3655s remaining, 1.2 samples/s
  [1800/6126] 1502s elapsed, ~3610s remaining, 1.2 samples/s
  [1850/6126] 1542s elapsed, ~3565s remaining, 1.2 samples/s
  [1900/6126] 1583s elapsed, ~3521s remaining, 1.2 samples/s
  [1950/6126] 1623s elapsed, ~3476s remaining, 1.2 samples/s
  [2000/6126] 1664s elapsed, ~3434s remaining, 1.2 samples/s
  [2050/6126] 1707s elapsed, ~3394s remaining, 1.2 samples/s
  [2100/6126] 1749s elapsed, ~3354s remaining, 1.2 samples/s
  [2150/6126] 1791s elapsed, ~3312s remaining, 1.2 samples/s
  [2200/6126] 1833s elapsed, ~3272s remaining, 1.2 samples/s
  [2250/6126] 1875s elapsed, ~3230s remaining, 1.2 samples/s
  [2300/6126] 1916s elapsed, ~3188s remaining, 1.2 samples/s
  [2350/6126] 1959s elapsed, ~3147s remaining, 1.2 samples/s
  [2400/6126] 2001s elapsed, ~3107s remaining, 1.2 samples/s
  [2450/6126] 2043s elapsed, ~3066s remaining, 1.2 samples/s
  [2500/6126] 2084s elapsed, ~3023s remaining, 1.2 samples/s
  [2550/6126] 2125s elapsed, ~2980s remaining, 1.2 samples/s
  [2600/6126] 2166s elapsed, ~2938s remaining, 1.2 samples/s
  [2650/6126] 2207s elapsed, ~2895s remaining, 1.2 samples/s
  [2700/6126] 2248s elapsed, ~2852s remaining, 1.2 samples/s
  [2750/6126] 2291s elapsed, ~2812s remaining, 1.2 samples/s
  [2800/6126] 2334s elapsed, ~2772s remaining, 1.2 samples/s
  [2850/6126] 2376s elapsed, ~2731s remaining, 1.2 samples/s
  [2900/6126] 2418s elapsed, ~2690s remaining, 1.2 samples/s
  [2950/6126] 2462s elapsed, ~2650s remaining, 1.2 samples/s
  [3000/6126] 2504s elapsed, ~2609s remaining, 1.2 samples/s
  [3050/6126] 2545s elapsed, ~2567s remaining, 1.2 samples/s
  [3100/6126] 2587s elapsed, ~2526s remaining, 1.2 samples/s
  [3150/6126] 2630s elapsed, ~2485s remaining, 1.2 samples/s
  [3200/6126] 2674s elapsed, ~2445s remaining, 1.2 samples/s
  [3250/6126] 2715s elapsed, ~2403s remaining, 1.2 samples/s
  [3300/6126] 2756s elapsed, ~2360s remaining, 1.2 samples/s
  [3350/6126] 2797s elapsed, ~2318s remaining, 1.2 samples/s
  [3400/6126] 2838s elapsed, ~2275s remaining, 1.2 samples/s
  [3450/6126] 2879s elapsed, ~2233s remaining, 1.2 samples/s
  [3500/6126] 2920s elapsed, ~2191s remaining, 1.2 samples/s
  [3550/6126] 2962s elapsed, ~2149s remaining, 1.2 samples/s
  [3600/6126] 3004s elapsed, ~2108s remaining, 1.2 samples/s
  [3650/6126] 3046s elapsed, ~2066s remaining, 1.2 samples/s
  [3700/6126] 3087s elapsed, ~2024s remaining, 1.2 samples/s
  [3750/6126] 3129s elapsed, ~1983s remaining, 1.2 samples/s
  [3800/6126] 3172s elapsed, ~1941s remaining, 1.2 samples/s
  [3850/6126] 3214s elapsed, ~1900s remaining, 1.2 samples/s
  [3900/6126] 3256s elapsed, ~1858s remaining, 1.2 samples/s
  [3950/6126] 3297s elapsed, ~1816s remaining, 1.2 samples/s
  [4000/6126] 3339s elapsed, ~1775s remaining, 1.2 samples/s
  [4050/6126] 3380s elapsed, ~1732s remaining, 1.2 samples/s
  [4100/6126] 3421s elapsed, ~1690s remaining, 1.2 samples/s
  [4150/6126] 3462s elapsed, ~1648s remaining, 1.2 samples/s
  [4200/6126] 3503s elapsed, ~1606s remaining, 1.2 samples/s
  [4250/6126] 3544s elapsed, ~1565s remaining, 1.2 samples/s
  [4300/6126] 3586s elapsed, ~1523s remaining, 1.2 samples/s
  [4350/6126] 3629s elapsed, ~1481s remaining, 1.2 samples/s
  [4400/6126] 3671s elapsed, ~1440s remaining, 1.2 samples/s
  [4450/6126] 3712s elapsed, ~1398s remaining, 1.2 samples/s
  [4500/6126] 3755s elapsed, ~1357s remaining, 1.2 samples/s
  [4550/6126] 3797s elapsed, ~1315s remaining, 1.2 samples/s
  [4600/6126] 3839s elapsed, ~1274s remaining, 1.2 samples/s
  [4650/6126] 3882s elapsed, ~1232s remaining, 1.2 samples/s
  [4700/6126] 3925s elapsed, ~1191s remaining, 1.2 samples/s
  [4750/6126] 3967s elapsed, ~1149s remaining, 1.2 samples/s
  [4800/6126] 4008s elapsed, ~1107s remaining, 1.2 samples/s
  [4850/6126] 4049s elapsed, ~1065s remaining, 1.2 samples/s
  [4900/6126] 4090s elapsed, ~1023s remaining, 1.2 samples/s
  [4950/6126] 4132s elapsed, ~982s remaining, 1.2 samples/s
  [5000/6126] 4172s elapsed, ~940s remaining, 1.2 samples/s
  [5050/6126] 4213s elapsed, ~898s remaining, 1.2 samples/s
  [5100/6126] 4254s elapsed, ~856s remaining, 1.2 samples/s
  [5150/6126] 4296s elapsed, ~814s remaining, 1.2 samples/s
  [5200/6126] 4338s elapsed, ~773s remaining, 1.2 samples/s
  [5250/6126] 4382s elapsed, ~731s remaining, 1.2 samples/s
  [5300/6126] 4425s elapsed, ~690s remaining, 1.2 samples/s
  [5350/6126] 4467s elapsed, ~648s remaining, 1.2 samples/s
  [5400/6126] 4509s elapsed, ~606s remaining, 1.2 samples/s
  [5450/6126] 4551s elapsed, ~564s remaining, 1.2 samples/s
  [5500/6126] 4593s elapsed, ~523s remaining, 1.2 samples/s
  [5550/6126] 4634s elapsed, ~481s remaining, 1.2 samples/s
  [5600/6126] 4676s elapsed, ~439s remaining, 1.2 samples/s
  [5650/6126] 4718s elapsed, ~397s remaining, 1.2 samples/s
  [5700/6126] 4759s elapsed, ~356s remaining, 1.2 samples/s
  [5750/6126] 4800s elapsed, ~314s remaining, 1.2 samples/s
  [5800/6126] 4841s elapsed, ~272s remaining, 1.2 samples/s
  [5850/6126] 4882s elapsed, ~230s remaining, 1.2 samples/s
  [5900/6126] 4923s elapsed, ~189s remaining, 1.2 samples/s
  [5950/6126] 4966s elapsed, ~147s remaining, 1.2 samples/s
  [6000/6126] 5009s elapsed, ~105s remaining, 1.2 samples/s
  [6050/6126] 5051s elapsed, ~63s remaining, 1.2 samples/s
  [6100/6126] 5093s elapsed, ~22s remaining, 1.2 samples/s
  [6126/6126] 5116s elapsed, ~0s remaining, 1.2 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\llama-3.2-11b\humanitarian\text_image\train
  Accuracy:           0.7613
  Weighted Precision: 0.7863
  Weighted Recall:    0.7613
  Weighted F1:        0.7567
  Macro Precision:    0.7040
  Macro Recall:       0.6175
  Macro F1:           0.6292
  Unparseable:        0

### Humanitarian Summary

In [8]:
show_summary("humanitarian")

Task: humanitarian
Model: llama-3.2-11b

     Modality  Split  Samples Accuracy Weighted F1 Macro F1  Unparseable
0   text_only   test      955   0.7414      0.7382   0.6343            0
1   text_only  train     5263   0.7372      0.7324   0.6165            0
2  image_only   test      955   0.7654      0.7571   0.6275            0
3  image_only  train     6126   0.7729      0.7679   0.6694            0
4  text_image   test      955   0.7424      0.7360   0.5947            0
5  text_image  train     6126   0.7613      0.7567   0.6292            0

## Cleanup — Free GPU Memory

In [9]:
del model, processor

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    print(f"GPU memory allocated: {torch.cuda.memory_allocated()/1e9:.1f} GB")
    print(f"GPU memory reserved:  {torch.cuda.memory_reserved()/1e9:.1f} GB")

print("\nAll 12 experiments complete.")

GPU memory allocated: 0.0 GB
GPU memory reserved:  0.0 GB

Note: If memory is still high, restart the kernel to fully release GPU memory.