# Zero-Shot Classification (Qwen3-VL-8B-Instruct)

Run zero-shot classification across **both tasks** and **all 3 modalities** (train + test splits).

**12 experiments total** (2 tasks × 3 modalities × 2 splits), run sequentially with cleanup between each.

| # | Task | Modality | Split | Output |
|---|------|----------|-------|--------|
| 1–6 | informative | text_only / image_only / text_image | test + train | `results/zeroshot/qwen3-vl-8b/informative/...` |
| 7–12 | humanitarian | text_only / image_only / text_image | test + train | `results/zeroshot/qwen3-vl-8b/humanitarian/...` |

## Setup

In [1]:
import sys, os, gc
sys.path.insert(0, os.path.abspath(".."))

import torch
from scripts.zeroshot_qwen import load_model, run_zeroshot

# Configuration
MODEL_ID = "Qwen/Qwen3-VL-8B-Instruct"
DATA_ROOT = os.path.abspath("../data")
OUTPUT_DIR = os.path.abspath("../results/zeroshot")

def cleanup(*vars_to_del):
    """Delete prediction variables and free GPU memory."""
    for v in vars_to_del:
        del v
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

# Load model once -- reused across all 12 experiments
model, processor = load_model(MODEL_ID)

Loading model: Qwen/Qwen3-VL-8B-Instruct (Qwen3VLForConditionalGeneration)

config.json: 0.00B [00:00, ?B/s]

D:\Workspace\Cotrain_CrisisMMD\.venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\anhtr\.cache\huggingface\hub\models--Qwen--Qwen3-VL-8B-Instruct. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/750 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

Model loaded on cuda:0

## Informative Task (6 experiments)

In [2]:
# 1. Informative -- text_only -- test
preds, _ = run_zeroshot(
    task="informative", modality="text_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_only\test.tsv
  [50/1534] 10s elapsed, ~287s remaining, 5.2 samples/s
  [100/1534] 18s elapsed, ~262s remaining, 5.5 samples/s
  [150/1534] 27s elapsed, ~249s remaining, 5.6 samples/s
  [200/1534] 35s elapsed, ~237s remaining, 5.6 samples/s
  [250/1534] 44s elapsed, ~226s remaining, 5.7 samples/s
  [300/1534] 52s elapsed, ~216s remaining, 5.7 samples/s
  [350/1534] 61s elapsed, ~206s remaining, 5.7 samples/s
  [400/1534] 70s elapsed, ~197s remaining, 5.8 samples/s
  [450/1534] 78s elapsed, ~188s remaining, 5.8 samples/s
  [500/1534] 87s elapsed, ~179s remaining, 5.8 samples/s
  [550/1534] 95s elapsed, ~170s remaining, 5.8 samples/s
  [600/1534] 103s elapsed, ~161s remaining, 5.8 samples/s
  [650/1534] 112s elapsed, ~152s remaining, 5.8 samples/s
  [700/1534] 120s elapsed, ~143s remaining, 5.8 samples/s
  [750/1534] 129s elapsed, ~135s remaining, 5.8 samples/s
  [800/1534] 137s elapsed, ~126s remaining, 5.8 samples/s
  [850/1534] 146s elapsed, ~117s remaining, 5.8 samples/s
  [900/1534] 154s elapsed, ~109s remaining, 5.8 samples/s
  [950/1534] 163s elapsed, ~100s remaining, 5.8 samples/s
  [1000/1534] 171s elapsed, ~91s remaining, 5.8 samples/s
  [1050/1534] 180s elapsed, ~83s remaining, 5.8 samples/s
  [1100/1534] 189s elapsed, ~75s remaining, 5.8 samples/s
  [1150/1534] 198s elapsed, ~66s remaining, 5.8 samples/s
  [1200/1534] 206s elapsed, ~57s remaining, 5.8 samples/s
  [1250/1534] 214s elapsed, ~49s remaining, 5.8 samples/s
  [1300/1534] 223s elapsed, ~40s remaining, 5.8 samples/s
  [1350/1534] 232s elapsed, ~32s remaining, 5.8 samples/s
  [1400/1534] 240s elapsed, ~23s remaining, 5.8 samples/s
  [1450/1534] 249s elapsed, ~14s remaining, 5.8 samples/s
  [1500/1534] 258s elapsed, ~6s remaining, 5.8 samples/s
  [1534/1534] 263s elapsed, ~0s remaining, 5.8 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\text_only\test
  Accuracy:           0.8188
  Weighted Precision: 0.8434
  Weighted Recall:    0.8188
  Weighted F1:        0.7987
  Macro Precision:    0.8693
  Macro Recall:       0.7313
  Macro F1:           0.7564
  Unparseable:        0

In [3]:
# 2. Informative -- text_only -- train
preds, _ = run_zeroshot(
    task="informative", modality="text_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 8293 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_only\train.tsv
  [50/8293] 9s elapsed, ~1405s remaining, 5.9 samples/s
  [100/8293] 17s elapsed, ~1392s remaining, 5.9 samples/s
  [150/8293] 25s elapsed, ~1383s remaining, 5.9 samples/s
  [200/8293] 34s elapsed, ~1386s remaining, 5.8 samples/s
  [250/8293] 43s elapsed, ~1380s remaining, 5.8 samples/s
  [300/8293] 52s elapsed, ~1372s remaining, 5.8 samples/s
  [350/8293] 60s elapsed, ~1366s remaining, 5.8 samples/s
  [400/8293] 69s elapsed, ~1356s remaining, 5.8 samples/s
  [450/8293] 77s elapsed, ~1347s remaining, 5.8 samples/s
  [500/8293] 86s elapsed, ~1339s remaining, 5.8 samples/s
  [550/8293] 94s elapsed, ~1330s remaining, 5.8 samples/s
  [600/8293] 103s elapsed, ~1322s remaining, 5.8 samples/s
  [650/8293] 112s elapsed, ~1317s remaining, 5.8 samples/s
  [700/8293] 121s elapsed, ~1310s remaining, 5.8 samples/s
  [750/8293] 129s elapsed, ~1300s remaining, 5.8 samples/s
  [800/8293] 138s elapsed, ~1292s remaining, 5.8 samples/s
  [850/8293] 147s elapsed, ~1283s remaining, 5.8 samples/s
  [900/8293] 155s elapsed, ~1274s remaining, 5.8 samples/s
  [950/8293] 164s elapsed, ~1267s remaining, 5.8 samples/s
  [1000/8293] 173s elapsed, ~1258s remaining, 5.8 samples/s
  [1050/8293] 181s elapsed, ~1249s remaining, 5.8 samples/s
  [1100/8293] 190s elapsed, ~1241s remaining, 5.8 samples/s
  [1150/8293] 198s elapsed, ~1231s remaining, 5.8 samples/s
  [1200/8293] 207s elapsed, ~1221s remaining, 5.8 samples/s
  [1250/8293] 215s elapsed, ~1214s remaining, 5.8 samples/s
  [1300/8293] 224s elapsed, ~1204s remaining, 5.8 samples/s
  [1350/8293] 233s elapsed, ~1196s remaining, 5.8 samples/s
  [1400/8293] 241s elapsed, ~1187s remaining, 5.8 samples/s
  [1450/8293] 250s elapsed, ~1179s remaining, 5.8 samples/s
  [1500/8293] 258s elapsed, ~1170s remaining, 5.8 samples/s
  [1550/8293] 267s elapsed, ~1162s remaining, 5.8 samples/s
  [1600/8293] 276s elapsed, ~1153s remaining, 5.8 samples/s
  [1650/8293] 284s elapsed, ~1144s remaining, 5.8 samples/s
  [1700/8293] 293s elapsed, ~1134s remaining, 5.8 samples/s
  [1750/8293] 301s elapsed, ~1126s remaining, 5.8 samples/s
  [1800/8293] 310s elapsed, ~1117s remaining, 5.8 samples/s
  [1850/8293] 318s elapsed, ~1109s remaining, 5.8 samples/s
  [1900/8293] 327s elapsed, ~1100s remaining, 5.8 samples/s
  [1950/8293] 335s elapsed, ~1091s remaining, 5.8 samples/s
  [2000/8293] 344s elapsed, ~1082s remaining, 5.8 samples/s
  [2050/8293] 353s elapsed, ~1075s remaining, 5.8 samples/s
  [2100/8293] 363s elapsed, ~1071s remaining, 5.8 samples/s
  [2150/8293] 374s elapsed, ~1068s remaining, 5.8 samples/s
  [2200/8293] 384s elapsed, ~1063s remaining, 5.7 samples/s
  [2250/8293] 394s elapsed, ~1058s remaining, 5.7 samples/s
  [2300/8293] 403s elapsed, ~1049s remaining, 5.7 samples/s
  [2350/8293] 411s elapsed, ~1040s remaining, 5.7 samples/s
  [2400/8293] 420s elapsed, ~1031s remaining, 5.7 samples/s
  [2450/8293] 429s elapsed, ~1022s remaining, 5.7 samples/s
  [2500/8293] 437s elapsed, ~1013s remaining, 5.7 samples/s
  [2550/8293] 446s elapsed, ~1004s remaining, 5.7 samples/s
  [2600/8293] 454s elapsed, ~995s remaining, 5.7 samples/s
  [2650/8293] 463s elapsed, ~986s remaining, 5.7 samples/s
  [2700/8293] 471s elapsed, ~976s remaining, 5.7 samples/s
  [2750/8293] 480s elapsed, ~967s remaining, 5.7 samples/s
  [2800/8293] 489s elapsed, ~959s remaining, 5.7 samples/s
  [2850/8293] 497s elapsed, ~950s remaining, 5.7 samples/s
  [2900/8293] 508s elapsed, ~944s remaining, 5.7 samples/s
  [2950/8293] 517s elapsed, ~937s remaining, 5.7 samples/s
  [3000/8293] 527s elapsed, ~930s remaining, 5.7 samples/s
  [3050/8293] 535s elapsed, ~921s remaining, 5.7 samples/s
  [3100/8293] 544s elapsed, ~912s remaining, 5.7 samples/s
  [3150/8293] 553s elapsed, ~903s remaining, 5.7 samples/s
  [3200/8293] 561s elapsed, ~893s remaining, 5.7 samples/s
  [3250/8293] 570s elapsed, ~884s remaining, 5.7 samples/s
  [3300/8293] 578s elapsed, ~875s remaining, 5.7 samples/s
  [3350/8293] 587s elapsed, ~866s remaining, 5.7 samples/s
  [3400/8293] 596s elapsed, ~857s remaining, 5.7 samples/s
  [3450/8293] 604s elapsed, ~848s remaining, 5.7 samples/s
  [3500/8293] 613s elapsed, ~840s remaining, 5.7 samples/s
  [3550/8293] 622s elapsed, ~830s remaining, 5.7 samples/s
  [3600/8293] 630s elapsed, ~821s remaining, 5.7 samples/s
  [3650/8293] 639s elapsed, ~812s remaining, 5.7 samples/s
  [3700/8293] 648s elapsed, ~804s remaining, 5.7 samples/s
  [3750/8293] 656s elapsed, ~795s remaining, 5.7 samples/s
  [3800/8293] 665s elapsed, ~786s remaining, 5.7 samples/s
  [3850/8293] 673s elapsed, ~777s remaining, 5.7 samples/s
  [3900/8293] 682s elapsed, ~768s remaining, 5.7 samples/s
  [3950/8293] 690s elapsed, ~759s remaining, 5.7 samples/s
  [4000/8293] 699s elapsed, ~750s remaining, 5.7 samples/s
  [4050/8293] 708s elapsed, ~741s remaining, 5.7 samples/s
  [4100/8293] 716s elapsed, ~732s remaining, 5.7 samples/s
  [4150/8293] 725s elapsed, ~724s remaining, 5.7 samples/s
  [4200/8293] 733s elapsed, ~715s remaining, 5.7 samples/s
  [4250/8293] 742s elapsed, ~706s remaining, 5.7 samples/s
  [4300/8293] 751s elapsed, ~697s remaining, 5.7 samples/s
  [4350/8293] 759s elapsed, ~688s remaining, 5.7 samples/s
  [4400/8293] 768s elapsed, ~679s remaining, 5.7 samples/s
  [4450/8293] 776s elapsed, ~670s remaining, 5.7 samples/s
  [4500/8293] 785s elapsed, ~662s remaining, 5.7 samples/s
  [4550/8293] 794s elapsed, ~653s remaining, 5.7 samples/s
  [4600/8293] 802s elapsed, ~644s remaining, 5.7 samples/s
  [4650/8293] 811s elapsed, ~635s remaining, 5.7 samples/s
  [4700/8293] 820s elapsed, ~627s remaining, 5.7 samples/s
  [4750/8293] 828s elapsed, ~618s remaining, 5.7 samples/s
  [4800/8293] 837s elapsed, ~609s remaining, 5.7 samples/s
  [4850/8293] 846s elapsed, ~600s remaining, 5.7 samples/s
  [4900/8293] 854s elapsed, ~592s remaining, 5.7 samples/s
  [4950/8293] 863s elapsed, ~583s remaining, 5.7 samples/s
  [5000/8293] 873s elapsed, ~575s remaining, 5.7 samples/s
  [5050/8293] 881s elapsed, ~566s remaining, 5.7 samples/s
  [5100/8293] 890s elapsed, ~557s remaining, 5.7 samples/s
  [5150/8293] 899s elapsed, ~548s remaining, 5.7 samples/s
  [5200/8293] 907s elapsed, ~540s remaining, 5.7 samples/s
  [5250/8293] 916s elapsed, ~531s remaining, 5.7 samples/s
  [5300/8293] 925s elapsed, ~522s remaining, 5.7 samples/s
  [5350/8293] 933s elapsed, ~513s remaining, 5.7 samples/s
  [5400/8293] 942s elapsed, ~505s remaining, 5.7 samples/s
  [5450/8293] 950s elapsed, ~496s remaining, 5.7 samples/s
  [5500/8293] 959s elapsed, ~487s remaining, 5.7 samples/s
  [5550/8293] 968s elapsed, ~478s remaining, 5.7 samples/s
  [5600/8293] 976s elapsed, ~469s remaining, 5.7 samples/s
  [5650/8293] 985s elapsed, ~461s remaining, 5.7 samples/s
  [5700/8293] 993s elapsed, ~452s remaining, 5.7 samples/s
  [5750/8293] 1002s elapsed, ~443s remaining, 5.7 samples/s
  [5800/8293] 1010s elapsed, ~434s remaining, 5.7 samples/s
  [5850/8293] 1019s elapsed, ~426s remaining, 5.7 samples/s
  [5900/8293] 1028s elapsed, ~417s remaining, 5.7 samples/s
  [5950/8293] 1036s elapsed, ~408s remaining, 5.7 samples/s
  [6000/8293] 1044s elapsed, ~399s remaining, 5.7 samples/s
  [6050/8293] 1053s elapsed, ~390s remaining, 5.7 samples/s
  [6100/8293] 1062s elapsed, ~382s remaining, 5.7 samples/s
  [6150/8293] 1070s elapsed, ~373s remaining, 5.7 samples/s
  [6200/8293] 1079s elapsed, ~364s remaining, 5.7 samples/s
  [6250/8293] 1087s elapsed, ~355s remaining, 5.7 samples/s
  [6300/8293] 1096s elapsed, ~347s remaining, 5.7 samples/s
  [6350/8293] 1104s elapsed, ~338s remaining, 5.8 samples/s
  [6400/8293] 1113s elapsed, ~329s remaining, 5.8 samples/s
  [6450/8293] 1122s elapsed, ~320s remaining, 5.8 samples/s
  [6500/8293] 1130s elapsed, ~312s remaining, 5.8 samples/s
  [6550/8293] 1139s elapsed, ~303s remaining, 5.8 samples/s
  [6600/8293] 1147s elapsed, ~294s remaining, 5.8 samples/s
  [6650/8293] 1156s elapsed, ~286s remaining, 5.8 samples/s
  [6700/8293] 1165s elapsed, ~277s remaining, 5.8 samples/s
  [6750/8293] 1173s elapsed, ~268s remaining, 5.8 samples/s
  [6800/8293] 1182s elapsed, ~259s remaining, 5.8 samples/s
  [6850/8293] 1191s elapsed, ~251s remaining, 5.8 samples/s
  [6900/8293] 1199s elapsed, ~242s remaining, 5.8 samples/s
  [6950/8293] 1208s elapsed, ~233s remaining, 5.8 samples/s
  [7000/8293] 1216s elapsed, ~225s remaining, 5.8 samples/s
  [7050/8293] 1225s elapsed, ~216s remaining, 5.8 samples/s
  [7100/8293] 1234s elapsed, ~207s remaining, 5.8 samples/s
  [7150/8293] 1242s elapsed, ~199s remaining, 5.8 samples/s
  [7200/8293] 1251s elapsed, ~190s remaining, 5.8 samples/s
  [7250/8293] 1260s elapsed, ~181s remaining, 5.8 samples/s
  [7300/8293] 1268s elapsed, ~173s remaining, 5.8 samples/s
  [7350/8293] 1277s elapsed, ~164s remaining, 5.8 samples/s
  [7400/8293] 1286s elapsed, ~155s remaining, 5.8 samples/s
  [7450/8293] 1294s elapsed, ~146s remaining, 5.8 samples/s
  [7500/8293] 1303s elapsed, ~138s remaining, 5.8 samples/s
  [7550/8293] 1312s elapsed, ~129s remaining, 5.8 samples/s
  [7600/8293] 1320s elapsed, ~120s remaining, 5.8 samples/s
  [7650/8293] 1329s elapsed, ~112s remaining, 5.8 samples/s
  [7700/8293] 1338s elapsed, ~103s remaining, 5.8 samples/s
  [7750/8293] 1346s elapsed, ~94s remaining, 5.8 samples/s
  [7800/8293] 1355s elapsed, ~86s remaining, 5.8 samples/s
  [7850/8293] 1363s elapsed, ~77s remaining, 5.8 samples/s
  [7900/8293] 1372s elapsed, ~68s remaining, 5.8 samples/s
  [7950/8293] 1380s elapsed, ~60s remaining, 5.8 samples/s
  [8000/8293] 1389s elapsed, ~51s remaining, 5.8 samples/s
  [8050/8293] 1398s elapsed, ~42s remaining, 5.8 samples/s
  [8100/8293] 1406s elapsed, ~34s remaining, 5.8 samples/s
  [8150/8293] 1415s elapsed, ~25s remaining, 5.8 samples/s
  [8200/8293] 1423s elapsed, ~16s remaining, 5.8 samples/s
  [8250/8293] 1432s elapsed, ~7s remaining, 5.8 samples/s
  [8293/8293] 1440s elapsed, ~0s remaining, 5.8 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\text_only\train
  Accuracy:           0.8002
  Weighted Precision: 0.8240
  Weighted Recall:    0.8002
  Weighted F1:        0.7763
  Macro Precision:    0.8472
  Macro Recall:       0.7085
  Macro F1:           0.7297
  Unparseable:        0

In [4]:
# 3. Informative -- image_only -- test
preds, _ = run_zeroshot(
    task="informative", modality="image_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\image_only\test.tsv
  [50/1534] 19s elapsed, ~565s remaining, 2.6 samples/s
  [100/1534] 37s elapsed, ~535s remaining, 2.7 samples/s
  [150/1534] 56s elapsed, ~513s remaining, 2.7 samples/s
  [200/1534] 74s elapsed, ~494s remaining, 2.7 samples/s
  [250/1534] 94s elapsed, ~485s remaining, 2.6 samples/s
  [300/1534] 114s elapsed, ~469s remaining, 2.6 samples/s
  [350/1534] 135s elapsed, ~456s remaining, 2.6 samples/s
  [400/1534] 155s elapsed, ~440s remaining, 2.6 samples/s
  [450/1534] 176s elapsed, ~424s remaining, 2.6 samples/s
  [500/1534] 195s elapsed, ~404s remaining, 2.6 samples/s
  [550/1534] 215s elapsed, ~384s remaining, 2.6 samples/s
  [600/1534] 235s elapsed, ~365s remaining, 2.6 samples/s
  [650/1534] 254s elapsed, ~345s remaining, 2.6 samples/s
  [700/1534] 275s elapsed, ~328s remaining, 2.5 samples/s
  [750/1534] 294s elapsed, ~308s remaining, 2.5 samples/s
  [800/1534] 314s elapsed, ~288s remaining, 2.5 samples/s
  [850/1534] 333s elapsed, ~268s remaining, 2.5 samples/s
  [900/1534] 353s elapsed, ~249s remaining, 2.5 samples/s
  [950/1534] 373s elapsed, ~229s remaining, 2.5 samples/s
  [1000/1534] 392s elapsed, ~209s remaining, 2.6 samples/s
  [1050/1534] 411s elapsed, ~189s remaining, 2.6 samples/s
  [1100/1534] 430s elapsed, ~170s remaining, 2.6 samples/s
  [1150/1534] 450s elapsed, ~150s remaining, 2.6 samples/s
  [1200/1534] 469s elapsed, ~131s remaining, 2.6 samples/s
  [1250/1534] 488s elapsed, ~111s remaining, 2.6 samples/s
  [1300/1534] 509s elapsed, ~92s remaining, 2.6 samples/s
  [1350/1534] 530s elapsed, ~72s remaining, 2.5 samples/s
  [1400/1534] 549s elapsed, ~53s remaining, 2.6 samples/s
  [1450/1534] 568s elapsed, ~33s remaining, 2.6 samples/s
  [1500/1534] 589s elapsed, ~13s remaining, 2.5 samples/s
  [1534/1534] 604s elapsed, ~0s remaining, 2.5 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\image_only\test
  Accuracy:           0.8638
  Weighted Precision: 0.8643
  Weighted Recall:    0.8638
  Weighted F1:        0.8640
  Macro Precision:    0.8450
  Macro Recall:       0.8474
  Macro F1:           0.8461
  Unparseable:        0

In [5]:
# 4. Informative -- image_only -- train
preds, _ = run_zeroshot(
    task="informative", modality="image_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 9601 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\image_only\train.tsv
  [50/9601] 22s elapsed, ~4296s remaining, 2.2 samples/s
  [100/9601] 44s elapsed, ~4164s remaining, 2.3 samples/s
  [150/9601] 63s elapsed, ~3963s remaining, 2.4 samples/s
  [200/9601] 86s elapsed, ~4044s remaining, 2.3 samples/s
  [250/9601] 110s elapsed, ~4104s remaining, 2.3 samples/s
  [300/9601] 130s elapsed, ~4045s remaining, 2.3 samples/s
  [350/9601] 154s elapsed, ~4065s remaining, 2.3 samples/s
  [400/9601] 177s elapsed, ~4064s remaining, 2.3 samples/s
  [450/9601] 198s elapsed, ~4033s remaining, 2.3 samples/s
  [500/9601] 224s elapsed, ~4079s remaining, 2.2 samples/s
  [550/9601] 245s elapsed, ~4032s remaining, 2.2 samples/s
  [600/9601] 266s elapsed, ~3989s remaining, 2.3 samples/s
  [650/9601] 288s elapsed, ~3966s remaining, 2.3 samples/s
  [700/9601] 313s elapsed, ~3981s remaining, 2.2 samples/s
  [750/9601] 339s elapsed, ~3997s remaining, 2.2 samples/s
  [800/9601] 361s elapsed, ~3972s remaining, 2.2 samples/s
  [850/9601] 383s elapsed, ~3940s remaining, 2.2 samples/s
  [900/9601] 408s elapsed, ~3947s remaining, 2.2 samples/s
  [950/9601] 434s elapsed, ~3949s remaining, 2.2 samples/s
  [1000/9601] 459s elapsed, ~3947s remaining, 2.2 samples/s
  [1050/9601] 484s elapsed, ~3938s remaining, 2.2 samples/s
  [1100/9601] 509s elapsed, ~3935s remaining, 2.2 samples/s
  [1150/9601] 533s elapsed, ~3917s remaining, 2.2 samples/s
  [1200/9601] 555s elapsed, ~3885s remaining, 2.2 samples/s
  [1250/9601] 577s elapsed, ~3857s remaining, 2.2 samples/s
  [1300/9601] 601s elapsed, ~3836s remaining, 2.2 samples/s
  [1350/9601] 624s elapsed, ~3816s remaining, 2.2 samples/s
  [1400/9601] 648s elapsed, ~3797s remaining, 2.2 samples/s
  [1450/9601] 671s elapsed, ~3773s remaining, 2.2 samples/s
  [1500/9601] 696s elapsed, ~3759s remaining, 2.2 samples/s
  [1550/9601] 720s elapsed, ~3739s remaining, 2.2 samples/s
  [1600/9601] 745s elapsed, ~3724s remaining, 2.1 samples/s
  [1650/9601] 769s elapsed, ~3705s remaining, 2.1 samples/s
  [1700/9601] 794s elapsed, ~3690s remaining, 2.1 samples/s
  [1750/9601] 818s elapsed, ~3671s remaining, 2.1 samples/s
  [1800/9601] 840s elapsed, ~3638s remaining, 2.1 samples/s
  [1850/9601] 863s elapsed, ~3617s remaining, 2.1 samples/s
  [1900/9601] 888s elapsed, ~3600s remaining, 2.1 samples/s
  [1950/9601] 913s elapsed, ~3581s remaining, 2.1 samples/s
  [2000/9601] 939s elapsed, ~3567s remaining, 2.1 samples/s
  [2050/9601] 962s elapsed, ~3543s remaining, 2.1 samples/s
  [2100/9601] 987s elapsed, ~3524s remaining, 2.1 samples/s
  [2150/9601] 1011s elapsed, ~3504s remaining, 2.1 samples/s
  [2200/9601] 1035s elapsed, ~3483s remaining, 2.1 samples/s
  [2250/9601] 1062s elapsed, ~3468s remaining, 2.1 samples/s
  [2300/9601] 1083s elapsed, ~3438s remaining, 2.1 samples/s
  [2350/9601] 1103s elapsed, ~3403s remaining, 2.1 samples/s
  [2400/9601] 1122s elapsed, ~3365s remaining, 2.1 samples/s
  [2450/9601] 1140s elapsed, ~3326s remaining, 2.1 samples/s
  [2500/9601] 1161s elapsed, ~3297s remaining, 2.2 samples/s
  [2550/9601] 1181s elapsed, ~3265s remaining, 2.2 samples/s
  [2600/9601] 1201s elapsed, ~3235s remaining, 2.2 samples/s
  [2650/9601] 1221s elapsed, ~3204s remaining, 2.2 samples/s
  [2700/9601] 1240s elapsed, ~3170s remaining, 2.2 samples/s
  [2750/9601] 1262s elapsed, ~3143s remaining, 2.2 samples/s
  [2800/9601] 1279s elapsed, ~3107s remaining, 2.2 samples/s
  [2850/9601] 1300s elapsed, ~3079s remaining, 2.2 samples/s
  [2900/9601] 1320s elapsed, ~3050s remaining, 2.2 samples/s
  [2950/9601] 1341s elapsed, ~3023s remaining, 2.2 samples/s
  [3000/9601] 1360s elapsed, ~2992s remaining, 2.2 samples/s
  [3050/9601] 1381s elapsed, ~2966s remaining, 2.2 samples/s
  [3100/9601] 1402s elapsed, ~2939s remaining, 2.2 samples/s
  [3150/9601] 1421s elapsed, ~2911s remaining, 2.2 samples/s
  [3200/9601] 1441s elapsed, ~2882s remaining, 2.2 samples/s
  [3250/9601] 1460s elapsed, ~2854s remaining, 2.2 samples/s
  [3300/9601] 1480s elapsed, ~2825s remaining, 2.2 samples/s
  [3350/9601] 1499s elapsed, ~2796s remaining, 2.2 samples/s
  [3400/9601] 1516s elapsed, ~2766s remaining, 2.2 samples/s
  [3450/9601] 1536s elapsed, ~2739s remaining, 2.2 samples/s
  [3500/9601] 1557s elapsed, ~2714s remaining, 2.2 samples/s
  [3550/9601] 1576s elapsed, ~2686s remaining, 2.3 samples/s
  [3600/9601] 1594s elapsed, ~2658s remaining, 2.3 samples/s
  [3650/9601] 1616s elapsed, ~2635s remaining, 2.3 samples/s
  [3700/9601] 1635s elapsed, ~2608s remaining, 2.3 samples/s
  [3750/9601] 1656s elapsed, ~2583s remaining, 2.3 samples/s
  [3800/9601] 1677s elapsed, ~2561s remaining, 2.3 samples/s
  [3850/9601] 1697s elapsed, ~2535s remaining, 2.3 samples/s
  [3900/9601] 1717s elapsed, ~2510s remaining, 2.3 samples/s
  [3950/9601] 1736s elapsed, ~2484s remaining, 2.3 samples/s
  [4000/9601] 1756s elapsed, ~2458s remaining, 2.3 samples/s
  [4050/9601] 1776s elapsed, ~2434s remaining, 2.3 samples/s
  [4100/9601] 1796s elapsed, ~2410s remaining, 2.3 samples/s
  [4150/9601] 1817s elapsed, ~2386s remaining, 2.3 samples/s
  [4200/9601] 1836s elapsed, ~2361s remaining, 2.3 samples/s
  [4250/9601] 1855s elapsed, ~2335s remaining, 2.3 samples/s
  [4300/9601] 1875s elapsed, ~2312s remaining, 2.3 samples/s
  [4350/9601] 1896s elapsed, ~2289s remaining, 2.3 samples/s
  [4400/9601] 1916s elapsed, ~2265s remaining, 2.3 samples/s
  [4450/9601] 1937s elapsed, ~2242s remaining, 2.3 samples/s
  [4500/9601] 1956s elapsed, ~2218s remaining, 2.3 samples/s
  [4550/9601] 1976s elapsed, ~2193s remaining, 2.3 samples/s
  [4600/9601] 1995s elapsed, ~2169s remaining, 2.3 samples/s
  [4650/9601] 2016s elapsed, ~2146s remaining, 2.3 samples/s
  [4700/9601] 2035s elapsed, ~2122s remaining, 2.3 samples/s
  [4750/9601] 2055s elapsed, ~2099s remaining, 2.3 samples/s
  [4800/9601] 2076s elapsed, ~2076s remaining, 2.3 samples/s
  [4850/9601] 2095s elapsed, ~2052s remaining, 2.3 samples/s
  [4900/9601] 2114s elapsed, ~2028s remaining, 2.3 samples/s
  [4950/9601] 2133s elapsed, ~2004s remaining, 2.3 samples/s
  [5000/9601] 2153s elapsed, ~1981s remaining, 2.3 samples/s
  [5050/9601] 2173s elapsed, ~1958s remaining, 2.3 samples/s
  [5100/9601] 2193s elapsed, ~1935s remaining, 2.3 samples/s
  [5150/9601] 2213s elapsed, ~1912s remaining, 2.3 samples/s
  [5200/9601] 2233s elapsed, ~1890s remaining, 2.3 samples/s
  [5250/9601] 2254s elapsed, ~1868s remaining, 2.3 samples/s
  [5300/9601] 2275s elapsed, ~1846s remaining, 2.3 samples/s
  [5350/9601] 2294s elapsed, ~1823s remaining, 2.3 samples/s
  [5400/9601] 2314s elapsed, ~1800s remaining, 2.3 samples/s
  [5450/9601] 2333s elapsed, ~1777s remaining, 2.3 samples/s
  [5500/9601] 2353s elapsed, ~1754s remaining, 2.3 samples/s
  [5550/9601] 2372s elapsed, ~1731s remaining, 2.3 samples/s
  [5600/9601] 2392s elapsed, ~1709s remaining, 2.3 samples/s
  [5650/9601] 2413s elapsed, ~1687s remaining, 2.3 samples/s
  [5700/9601] 2432s elapsed, ~1665s remaining, 2.3 samples/s
  [5750/9601] 2451s elapsed, ~1641s remaining, 2.3 samples/s
  [5800/9601] 2471s elapsed, ~1619s remaining, 2.3 samples/s
  [5850/9601] 2489s elapsed, ~1596s remaining, 2.4 samples/s
  [5900/9601] 2510s elapsed, ~1574s remaining, 2.4 samples/s
  [5950/9601] 2530s elapsed, ~1553s remaining, 2.4 samples/s
  [6000/9601] 2550s elapsed, ~1530s remaining, 2.4 samples/s
  [6050/9601] 2570s elapsed, ~1509s remaining, 2.4 samples/s
  [6100/9601] 2589s elapsed, ~1486s remaining, 2.4 samples/s
  [6150/9601] 2611s elapsed, ~1465s remaining, 2.4 samples/s
  [6200/9601] 2631s elapsed, ~1443s remaining, 2.4 samples/s
  [6250/9601] 2651s elapsed, ~1422s remaining, 2.4 samples/s
  [6300/9601] 2670s elapsed, ~1399s remaining, 2.4 samples/s
  [6350/9601] 2690s elapsed, ~1377s remaining, 2.4 samples/s
  [6400/9601] 2710s elapsed, ~1355s remaining, 2.4 samples/s
  [6450/9601] 2730s elapsed, ~1334s remaining, 2.4 samples/s
  [6500/9601] 2749s elapsed, ~1312s remaining, 2.4 samples/s
  [6550/9601] 2769s elapsed, ~1290s remaining, 2.4 samples/s
  [6600/9601] 2790s elapsed, ~1269s remaining, 2.4 samples/s
  [6650/9601] 2811s elapsed, ~1247s remaining, 2.4 samples/s
  [6700/9601] 2832s elapsed, ~1226s remaining, 2.4 samples/s
  [6750/9601] 2852s elapsed, ~1205s remaining, 2.4 samples/s
  [6800/9601] 2871s elapsed, ~1183s remaining, 2.4 samples/s
  [6850/9601] 2890s elapsed, ~1161s remaining, 2.4 samples/s
  [6900/9601] 2909s elapsed, ~1139s remaining, 2.4 samples/s
  [6950/9601] 2930s elapsed, ~1117s remaining, 2.4 samples/s
  [7000/9601] 2950s elapsed, ~1096s remaining, 2.4 samples/s
  [7050/9601] 2969s elapsed, ~1074s remaining, 2.4 samples/s
  [7100/9601] 2989s elapsed, ~1053s remaining, 2.4 samples/s
  [7150/9601] 3007s elapsed, ~1031s remaining, 2.4 samples/s
  [7200/9601] 3027s elapsed, ~1009s remaining, 2.4 samples/s
  [7250/9601] 3047s elapsed, ~988s remaining, 2.4 samples/s
  [7300/9601] 3067s elapsed, ~967s remaining, 2.4 samples/s
  [7350/9601] 3086s elapsed, ~945s remaining, 2.4 samples/s
  [7400/9601] 3106s elapsed, ~924s remaining, 2.4 samples/s
  [7450/9601] 3127s elapsed, ~903s remaining, 2.4 samples/s
  [7500/9601] 3148s elapsed, ~882s remaining, 2.4 samples/s
  [7550/9601] 3168s elapsed, ~861s remaining, 2.4 samples/s
  [7600/9601] 3187s elapsed, ~839s remaining, 2.4 samples/s
  [7650/9601] 3208s elapsed, ~818s remaining, 2.4 samples/s
  [7700/9601] 3228s elapsed, ~797s remaining, 2.4 samples/s
  [7750/9601] 3249s elapsed, ~776s remaining, 2.4 samples/s
  [7800/9601] 3269s elapsed, ~755s remaining, 2.4 samples/s
  [7850/9601] 3289s elapsed, ~734s remaining, 2.4 samples/s
  [7900/9601] 3308s elapsed, ~712s remaining, 2.4 samples/s
  [7950/9601] 3327s elapsed, ~691s remaining, 2.4 samples/s
  [8000/9601] 3347s elapsed, ~670s remaining, 2.4 samples/s
  [8050/9601] 3367s elapsed, ~649s remaining, 2.4 samples/s
  [8100/9601] 3386s elapsed, ~628s remaining, 2.4 samples/s
  [8150/9601] 3405s elapsed, ~606s remaining, 2.4 samples/s
  [8200/9601] 3425s elapsed, ~585s remaining, 2.4 samples/s
  [8250/9601] 3442s elapsed, ~564s remaining, 2.4 samples/s
  [8300/9601] 3464s elapsed, ~543s remaining, 2.4 samples/s
  [8350/9601] 3483s elapsed, ~522s remaining, 2.4 samples/s
  [8400/9601] 3505s elapsed, ~501s remaining, 2.4 samples/s
  [8450/9601] 3525s elapsed, ~480s remaining, 2.4 samples/s
  [8500/9601] 3545s elapsed, ~459s remaining, 2.4 samples/s
  [8550/9601] 3566s elapsed, ~438s remaining, 2.4 samples/s
  [8600/9601] 3585s elapsed, ~417s remaining, 2.4 samples/s
  [8650/9601] 3607s elapsed, ~397s remaining, 2.4 samples/s
  [8700/9601] 3628s elapsed, ~376s remaining, 2.4 samples/s
  [8750/9601] 3648s elapsed, ~355s remaining, 2.4 samples/s
  [8800/9601] 3669s elapsed, ~334s remaining, 2.4 samples/s
  [8850/9601] 3689s elapsed, ~313s remaining, 2.4 samples/s
  [8900/9601] 3710s elapsed, ~292s remaining, 2.4 samples/s
  [8950/9601] 3731s elapsed, ~271s remaining, 2.4 samples/s
  [9000/9601] 3752s elapsed, ~251s remaining, 2.4 samples/s
  [9050/9601] 3771s elapsed, ~230s remaining, 2.4 samples/s
  [9100/9601] 3790s elapsed, ~209s remaining, 2.4 samples/s
  [9150/9601] 3809s elapsed, ~188s remaining, 2.4 samples/s
  [9200/9601] 3829s elapsed, ~167s remaining, 2.4 samples/s
  [9250/9601] 3849s elapsed, ~146s remaining, 2.4 samples/s
  [9300/9601] 3869s elapsed, ~125s remaining, 2.4 samples/s
  [9350/9601] 3890s elapsed, ~104s remaining, 2.4 samples/s
  [9400/9601] 3909s elapsed, ~84s remaining, 2.4 samples/s
  [9450/9601] 3930s elapsed, ~63s remaining, 2.4 samples/s
  [9500/9601] 3949s elapsed, ~42s remaining, 2.4 samples/s
  [9550/9601] 3970s elapsed, ~21s remaining, 2.4 samples/s
  [9600/9601] 3989s elapsed, ~0s remaining, 2.4 samples/s
  [9601/9601] 3989s elapsed, ~0s remaining, 2.4 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\image_only\train
  Accuracy:           0.8547
  Weighted Precision: 0.8563
  Weighted Recall:    0.8547
  Weighted F1:        0.8554
  Macro Precision:    0.8365
  Macro Recall:       0.8427
  Macro F1:           0.8394
  Unparseable:        0

In [6]:
# 5. Informative -- text_image -- test
preds, _ = run_zeroshot(
    task="informative", modality="text_image", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 1534 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_image\test.tsv
  [50/1534] 19s elapsed, ~577s remaining, 2.6 samples/s
  [100/1534] 38s elapsed, ~550s remaining, 2.6 samples/s
  [150/1534] 57s elapsed, ~529s remaining, 2.6 samples/s
  [200/1534] 76s elapsed, ~509s remaining, 2.6 samples/s
  [250/1534] 98s elapsed, ~502s remaining, 2.6 samples/s
  [300/1534] 118s elapsed, ~486s remaining, 2.5 samples/s
  [350/1534] 140s elapsed, ~473s remaining, 2.5 samples/s
  [400/1534] 161s elapsed, ~456s remaining, 2.5 samples/s
  [450/1534] 183s elapsed, ~440s remaining, 2.5 samples/s
  [500/1534] 203s elapsed, ~419s remaining, 2.5 samples/s
  [550/1534] 222s elapsed, ~398s remaining, 2.5 samples/s
  [600/1534] 243s elapsed, ~378s remaining, 2.5 samples/s
  [650/1534] 262s elapsed, ~357s remaining, 2.5 samples/s
  [700/1534] 284s elapsed, ~339s remaining, 2.5 samples/s
  [750/1534] 304s elapsed, ~318s remaining, 2.5 samples/s
  [800/1534] 325s elapsed, ~298s remaining, 2.5 samples/s
  [850/1534] 345s elapsed, ~277s remaining, 2.5 samples/s
  [900/1534] 365s elapsed, ~257s remaining, 2.5 samples/s
  [950/1534] 386s elapsed, ~237s remaining, 2.5 samples/s
  [1000/1534] 405s elapsed, ~217s remaining, 2.5 samples/s
  [1050/1534] 425s elapsed, ~196s remaining, 2.5 samples/s
  [1100/1534] 445s elapsed, ~176s remaining, 2.5 samples/s
  [1150/1534] 466s elapsed, ~156s remaining, 2.5 samples/s
  [1200/1534] 486s elapsed, ~135s remaining, 2.5 samples/s
  [1250/1534] 506s elapsed, ~115s remaining, 2.5 samples/s
  [1300/1534] 527s elapsed, ~95s remaining, 2.5 samples/s
  [1350/1534] 549s elapsed, ~75s remaining, 2.5 samples/s
  [1400/1534] 570s elapsed, ~55s remaining, 2.5 samples/s
  [1450/1534] 591s elapsed, ~34s remaining, 2.5 samples/s
  [1500/1534] 614s elapsed, ~14s remaining, 2.4 samples/s
  [1534/1534] 630s elapsed, ~0s remaining, 2.4 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\text_image\test
  Accuracy:           0.8429
  Weighted Precision: 0.8590
  Weighted Recall:    0.8429
  Weighted F1:        0.8300
  Macro Precision:    0.8796
  Macro Recall:       0.7700
  Macro F1:           0.7967
  Unparseable:        0

In [7]:
# 6. Informative -- text_image -- train
preds, _ = run_zeroshot(
    task="informative", modality="text_image", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 9601 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\informative\text_image\train.tsv
  [50/9601] 24s elapsed, ~4531s remaining, 2.1 samples/s
  [100/9601] 47s elapsed, ~4425s remaining, 2.1 samples/s
  [150/9601] 67s elapsed, ~4226s remaining, 2.2 samples/s
  [200/9601] 91s elapsed, ~4299s remaining, 2.2 samples/s
  [250/9601] 116s elapsed, ~4336s remaining, 2.2 samples/s
  [300/9601] 138s elapsed, ~4268s remaining, 2.2 samples/s
  [350/9601] 163s elapsed, ~4297s remaining, 2.2 samples/s
  [400/9601] 187s elapsed, ~4295s remaining, 2.1 samples/s
  [450/9601] 209s elapsed, ~4259s remaining, 2.1 samples/s
  [500/9601] 236s elapsed, ~4302s remaining, 2.1 samples/s
  [550/9601] 259s elapsed, ~4257s remaining, 2.1 samples/s
  [600/9601] 280s elapsed, ~4206s remaining, 2.1 samples/s
  [650/9601] 304s elapsed, ~4182s remaining, 2.1 samples/s
  [700/9601] 330s elapsed, ~4196s remaining, 2.1 samples/s
  [750/9601] 358s elapsed, ~4223s remaining, 2.1 samples/s
  [800/9601] 381s elapsed, ~4193s remaining, 2.1 samples/s
  [850/9601] 404s elapsed, ~4157s remaining, 2.1 samples/s
  [900/9601] 430s elapsed, ~4161s remaining, 2.1 samples/s
  [950/9601] 457s elapsed, ~4160s remaining, 2.1 samples/s
  [1000/9601] 483s elapsed, ~4157s remaining, 2.1 samples/s
  [1050/9601] 509s elapsed, ~4145s remaining, 2.1 samples/s
  [1100/9601] 535s elapsed, ~4138s remaining, 2.1 samples/s
  [1150/9601] 560s elapsed, ~4117s remaining, 2.1 samples/s
  [1200/9601] 583s elapsed, ~4083s remaining, 2.1 samples/s
  [1250/9601] 607s elapsed, ~4055s remaining, 2.1 samples/s
  [1300/9601] 632s elapsed, ~4036s remaining, 2.1 samples/s
  [1350/9601] 657s elapsed, ~4014s remaining, 2.1 samples/s
  [1400/9601] 681s elapsed, ~3992s remaining, 2.1 samples/s
  [1450/9601] 705s elapsed, ~3965s remaining, 2.1 samples/s
  [1500/9601] 731s elapsed, ~3948s remaining, 2.1 samples/s
  [1550/9601] 756s elapsed, ~3925s remaining, 2.1 samples/s
  [1600/9601] 782s elapsed, ~3909s remaining, 2.0 samples/s
  [1650/9601] 807s elapsed, ~3887s remaining, 2.0 samples/s
  [1700/9601] 833s elapsed, ~3870s remaining, 2.0 samples/s
  [1750/9601] 858s elapsed, ~3850s remaining, 2.0 samples/s
  [1800/9601] 881s elapsed, ~3818s remaining, 2.0 samples/s
  [1850/9601] 906s elapsed, ~3798s remaining, 2.0 samples/s
  [1900/9601] 934s elapsed, ~3784s remaining, 2.0 samples/s
  [1950/9601] 960s elapsed, ~3766s remaining, 2.0 samples/s
  [2000/9601] 988s elapsed, ~3755s remaining, 2.0 samples/s
  [2050/9601] 1012s elapsed, ~3727s remaining, 2.0 samples/s
  [2100/9601] 1038s elapsed, ~3706s remaining, 2.0 samples/s
  [2150/9601] 1063s elapsed, ~3684s remaining, 2.0 samples/s
  [2200/9601] 1088s elapsed, ~3661s remaining, 2.0 samples/s
  [2250/9601] 1116s elapsed, ~3645s remaining, 2.0 samples/s
  [2300/9601] 1139s elapsed, ~3615s remaining, 2.0 samples/s
  [2350/9601] 1159s elapsed, ~3577s remaining, 2.0 samples/s
  [2400/9601] 1179s elapsed, ~3537s remaining, 2.0 samples/s
  [2450/9601] 1198s elapsed, ~3496s remaining, 2.0 samples/s
  [2500/9601] 1220s elapsed, ~3465s remaining, 2.0 samples/s
  [2550/9601] 1241s elapsed, ~3431s remaining, 2.1 samples/s
  [2600/9601] 1263s elapsed, ~3400s remaining, 2.1 samples/s
  [2650/9601] 1283s elapsed, ~3366s remaining, 2.1 samples/s
  [2700/9601] 1303s elapsed, ~3331s remaining, 2.1 samples/s
  [2750/9601] 1326s elapsed, ~3303s remaining, 2.1 samples/s
  [2800/9601] 1344s elapsed, ~3264s remaining, 2.1 samples/s
  [2850/9601] 1366s elapsed, ~3235s remaining, 2.1 samples/s
  [2900/9601] 1387s elapsed, ~3205s remaining, 2.1 samples/s
  [2950/9601] 1409s elapsed, ~3176s remaining, 2.1 samples/s
  [3000/9601] 1429s elapsed, ~3143s remaining, 2.1 samples/s
  [3050/9601] 1451s elapsed, ~3116s remaining, 2.1 samples/s
  [3100/9601] 1472s elapsed, ~3087s remaining, 2.1 samples/s
  [3150/9601] 1493s elapsed, ~3057s remaining, 2.1 samples/s
  [3200/9601] 1513s elapsed, ~3027s remaining, 2.1 samples/s
  [3250/9601] 1533s elapsed, ~2996s remaining, 2.1 samples/s
  [3300/9601] 1554s elapsed, ~2967s remaining, 2.1 samples/s
  [3350/9601] 1574s elapsed, ~2937s remaining, 2.1 samples/s
  [3400/9601] 1593s elapsed, ~2905s remaining, 2.1 samples/s
  [3450/9601] 1614s elapsed, ~2878s remaining, 2.1 samples/s
  [3500/9601] 1637s elapsed, ~2853s remaining, 2.1 samples/s
  [3550/9601] 1657s elapsed, ~2825s remaining, 2.1 samples/s
  [3600/9601] 1677s elapsed, ~2795s remaining, 2.1 samples/s
  [3650/9601] 1699s elapsed, ~2771s remaining, 2.1 samples/s
  [3700/9601] 1719s elapsed, ~2742s remaining, 2.2 samples/s
  [3750/9601] 1741s elapsed, ~2716s remaining, 2.2 samples/s
  [3800/9601] 1763s elapsed, ~2692s remaining, 2.2 samples/s
  [3850/9601] 1784s elapsed, ~2665s remaining, 2.2 samples/s
  [3900/9601] 1804s elapsed, ~2638s remaining, 2.2 samples/s
  [3950/9601] 1824s elapsed, ~2610s remaining, 2.2 samples/s
  [4000/9601] 1845s elapsed, ~2583s remaining, 2.2 samples/s
  [4050/9601] 1866s elapsed, ~2558s remaining, 2.2 samples/s
  [4100/9601] 1887s elapsed, ~2532s remaining, 2.2 samples/s
  [4150/9601] 1908s elapsed, ~2507s remaining, 2.2 samples/s
  [4200/9601] 1929s elapsed, ~2480s remaining, 2.2 samples/s
  [4250/9601] 1949s elapsed, ~2454s remaining, 2.2 samples/s
  [4300/9601] 1970s elapsed, ~2429s remaining, 2.2 samples/s
  [4350/9601] 1992s elapsed, ~2405s remaining, 2.2 samples/s
  [4400/9601] 2012s elapsed, ~2379s remaining, 2.2 samples/s
  [4450/9601] 2034s elapsed, ~2355s remaining, 2.2 samples/s
  [4500/9601] 2055s elapsed, ~2329s remaining, 2.2 samples/s
  [4550/9601] 2075s elapsed, ~2303s remaining, 2.2 samples/s
  [4600/9601] 2095s elapsed, ~2278s remaining, 2.2 samples/s
  [4650/9601] 2116s elapsed, ~2253s remaining, 2.2 samples/s
  [4700/9601] 2137s elapsed, ~2228s remaining, 2.2 samples/s
  [4750/9601] 2158s elapsed, ~2204s remaining, 2.2 samples/s
  [4800/9601] 2179s elapsed, ~2180s remaining, 2.2 samples/s
  [4850/9601] 2199s elapsed, ~2154s remaining, 2.2 samples/s
  [4900/9601] 2220s elapsed, ~2129s remaining, 2.2 samples/s
  [4950/9601] 2240s elapsed, ~2104s remaining, 2.2 samples/s
  [5000/9601] 2261s elapsed, ~2081s remaining, 2.2 samples/s
  [5050/9601] 2282s elapsed, ~2057s remaining, 2.2 samples/s
  [5100/9601] 2304s elapsed, ~2033s remaining, 2.2 samples/s
  [5150/9601] 2324s elapsed, ~2009s remaining, 2.2 samples/s
  [5200/9601] 2346s elapsed, ~1985s remaining, 2.2 samples/s
  [5250/9601] 2368s elapsed, ~1963s remaining, 2.2 samples/s
  [5300/9601] 2390s elapsed, ~1940s remaining, 2.2 samples/s
  [5350/9601] 2411s elapsed, ~1916s remaining, 2.2 samples/s
  [5400/9601] 2432s elapsed, ~1892s remaining, 2.2 samples/s
  [5450/9601] 2452s elapsed, ~1868s remaining, 2.2 samples/s
  [5500/9601] 2474s elapsed, ~1845s remaining, 2.2 samples/s
  [5550/9601] 2494s elapsed, ~1820s remaining, 2.2 samples/s
  [5600/9601] 2515s elapsed, ~1797s remaining, 2.2 samples/s
  [5650/9601] 2537s elapsed, ~1774s remaining, 2.2 samples/s
  [5700/9601] 2558s elapsed, ~1750s remaining, 2.2 samples/s
  [5750/9601] 2578s elapsed, ~1726s remaining, 2.2 samples/s
  [5800/9601] 2599s elapsed, ~1703s remaining, 2.2 samples/s
  [5850/9601] 2618s elapsed, ~1679s remaining, 2.2 samples/s
  [5900/9601] 2640s elapsed, ~1656s remaining, 2.2 samples/s
  [5950/9601] 2662s elapsed, ~1633s remaining, 2.2 samples/s
  [6000/9601] 2682s elapsed, ~1610s remaining, 2.2 samples/s
  [6050/9601] 2704s elapsed, ~1587s remaining, 2.2 samples/s
  [6100/9601] 2724s elapsed, ~1563s remaining, 2.2 samples/s
  [6150/9601] 2746s elapsed, ~1541s remaining, 2.2 samples/s
  [6200/9601] 2768s elapsed, ~1518s remaining, 2.2 samples/s
  [6250/9601] 2789s elapsed, ~1496s remaining, 2.2 samples/s
  [6300/9601] 2809s elapsed, ~1472s remaining, 2.2 samples/s
  [6350/9601] 2830s elapsed, ~1449s remaining, 2.2 samples/s
  [6400/9601] 2851s elapsed, ~1426s remaining, 2.2 samples/s
  [6450/9601] 2873s elapsed, ~1403s remaining, 2.2 samples/s
  [6500/9601] 2893s elapsed, ~1380s remaining, 2.2 samples/s
  [6550/9601] 2913s elapsed, ~1357s remaining, 2.2 samples/s
  [6600/9601] 2935s elapsed, ~1335s remaining, 2.2 samples/s
  [6650/9601] 2957s elapsed, ~1312s remaining, 2.2 samples/s
  [6700/9601] 2980s elapsed, ~1290s remaining, 2.2 samples/s
  [6750/9601] 3001s elapsed, ~1268s remaining, 2.2 samples/s
  [6800/9601] 3021s elapsed, ~1244s remaining, 2.3 samples/s
  [6850/9601] 3041s elapsed, ~1221s remaining, 2.3 samples/s
  [6900/9601] 3061s elapsed, ~1198s remaining, 2.3 samples/s
  [6950/9601] 3083s elapsed, ~1176s remaining, 2.3 samples/s
  [7000/9601] 3104s elapsed, ~1154s remaining, 2.3 samples/s
  [7050/9601] 3125s elapsed, ~1131s remaining, 2.3 samples/s
  [7100/9601] 3146s elapsed, ~1108s remaining, 2.3 samples/s
  [7150/9601] 3165s elapsed, ~1085s remaining, 2.3 samples/s
  [7200/9601] 3186s elapsed, ~1062s remaining, 2.3 samples/s
  [7250/9601] 3207s elapsed, ~1040s remaining, 2.3 samples/s
  [7300/9601] 3229s elapsed, ~1018s remaining, 2.3 samples/s
  [7350/9601] 3249s elapsed, ~995s remaining, 2.3 samples/s
  [7400/9601] 3270s elapsed, ~972s remaining, 2.3 samples/s
  [7450/9601] 3292s elapsed, ~950s remaining, 2.3 samples/s
  [7500/9601] 3314s elapsed, ~928s remaining, 2.3 samples/s
  [7550/9601] 3336s elapsed, ~906s remaining, 2.3 samples/s
  [7600/9601] 3355s elapsed, ~883s remaining, 2.3 samples/s
  [7650/9601] 3377s elapsed, ~861s remaining, 2.3 samples/s
  [7700/9601] 3398s elapsed, ~839s remaining, 2.3 samples/s
  [7750/9601] 3420s elapsed, ~817s remaining, 2.3 samples/s
  [7800/9601] 3441s elapsed, ~794s remaining, 2.3 samples/s
  [7850/9601] 3462s elapsed, ~772s remaining, 2.3 samples/s
  [7900/9601] 3483s elapsed, ~750s remaining, 2.3 samples/s
  [7950/9601] 3503s elapsed, ~727s remaining, 2.3 samples/s
  [8000/9601] 3523s elapsed, ~705s remaining, 2.3 samples/s
  [8050/9601] 3545s elapsed, ~683s remaining, 2.3 samples/s
  [8100/9601] 3566s elapsed, ~661s remaining, 2.3 samples/s
  [8150/9601] 3585s elapsed, ~638s remaining, 2.3 samples/s
  [8200/9601] 3606s elapsed, ~616s remaining, 2.3 samples/s
  [8250/9601] 3624s elapsed, ~593s remaining, 2.3 samples/s
  [8300/9601] 3646s elapsed, ~572s remaining, 2.3 samples/s
  [8350/9601] 3668s elapsed, ~549s remaining, 2.3 samples/s
  [8400/9601] 3688s elapsed, ~527s remaining, 2.3 samples/s
  [8450/9601] 3709s elapsed, ~505s remaining, 2.3 samples/s
  [8500/9601] 3729s elapsed, ~483s remaining, 2.3 samples/s
  [8550/9601] 3751s elapsed, ~461s remaining, 2.3 samples/s
  [8600/9601] 3772s elapsed, ~439s remaining, 2.3 samples/s
  [8650/9601] 3795s elapsed, ~417s remaining, 2.3 samples/s
  [8700/9601] 3817s elapsed, ~395s remaining, 2.3 samples/s
  [8750/9601] 3837s elapsed, ~373s remaining, 2.3 samples/s
  [8800/9601] 3859s elapsed, ~351s remaining, 2.3 samples/s
  [8850/9601] 3880s elapsed, ~329s remaining, 2.3 samples/s
  [8900/9601] 3902s elapsed, ~307s remaining, 2.3 samples/s
  [8950/9601] 3924s elapsed, ~285s remaining, 2.3 samples/s
  [9000/9601] 3946s elapsed, ~264s remaining, 2.3 samples/s
  [9050/9601] 3966s elapsed, ~241s remaining, 2.3 samples/s
  [9100/9601] 3986s elapsed, ~219s remaining, 2.3 samples/s
  [9150/9601] 4006s elapsed, ~197s remaining, 2.3 samples/s
  [9200/9601] 4027s elapsed, ~176s remaining, 2.3 samples/s
  [9250/9601] 4048s elapsed, ~154s remaining, 2.3 samples/s
  [9300/9601] 4069s elapsed, ~132s remaining, 2.3 samples/s
  [9350/9601] 4090s elapsed, ~110s remaining, 2.3 samples/s
  [9400/9601] 4111s elapsed, ~88s remaining, 2.3 samples/s
  [9450/9601] 4132s elapsed, ~66s remaining, 2.3 samples/s
  [9500/9601] 4152s elapsed, ~44s remaining, 2.3 samples/s
  [9550/9601] 4174s elapsed, ~22s remaining, 2.3 samples/s
  [9600/9601] 4194s elapsed, ~0s remaining, 2.3 samples/s
  [9601/9601] 4194s elapsed, ~0s remaining, 2.3 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\informative\text_image\train
  Accuracy:           0.8276
  Weighted Precision: 0.8481
  Weighted Recall:    0.8276
  Weighted F1:        0.8121
  Macro Precision:    0.8701
  Macro Recall:       0.7542
  Macro F1:           0.7785
  Unparseable:        0

### Informative Summary

In [8]:
import json
import pandas as pd
from pathlib import Path
from scripts.zeroshot_qwen import model_slug

def show_summary(task):
    slug = model_slug(MODEL_ID)
    results_dir = Path(OUTPUT_DIR) / slug / task
    modalities = ["text_only", "image_only", "text_image"]
    splits = ["test", "train"]
    rows = []
    for modality in modalities:
        for split in splits:
            metrics_path = results_dir / modality / split / "metrics.json"
            if metrics_path.exists():
                m = json.loads(metrics_path.read_text())
                rows.append({
                    "Modality": m["modality"], "Split": m["split"],
                    "Samples": m["num_samples"],
                    "Accuracy": f"{m['accuracy']:.4f}",
                    "Weighted F1": f"{m['weighted_f1']:.4f}",
                    "Macro F1": f"{m['macro_f1']:.4f}",
                    "Unparseable": m["num_unparseable"],
                })
            else:
                rows.append({
                    "Modality": modality, "Split": split,
                    "Samples": "-", "Accuracy": "-",
                    "Weighted F1": "-", "Macro F1": "-", "Unparseable": "-",
                })
    print(f"Task: {task}")
    print(f"Model: {slug}\n")
    display(pd.DataFrame(rows))

show_summary("informative")

Task: informative
Model: qwen3-vl-8b

     Modality  Split  Samples Accuracy Weighted F1 Macro F1  Unparseable
0   text_only   test     1534   0.8188      0.7987   0.7564            0
1   text_only  train     8293   0.8002      0.7763   0.7297            0
2  image_only   test     1534   0.8638      0.8640   0.8461            0
3  image_only  train     9601   0.8547      0.8554   0.8394            0
4  text_image   test     1534   0.8429      0.8300   0.7967            0
5  text_image  train     9601   0.8276      0.8121   0.7785            0

## Humanitarian Task (6 experiments)

In [9]:
# 7. Humanitarian -- text_only -- test
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_only\test.tsv
  [50/955] 12s elapsed, ~221s remaining, 4.1 samples/s
  [100/955] 25s elapsed, ~211s remaining, 4.0 samples/s
  [150/955] 37s elapsed, ~199s remaining, 4.0 samples/s
  [200/955] 50s elapsed, ~187s remaining, 4.0 samples/s
  [250/955] 62s elapsed, ~174s remaining, 4.0 samples/s
  [300/955] 74s elapsed, ~162s remaining, 4.0 samples/s
  [350/955] 86s elapsed, ~149s remaining, 4.0 samples/s
  [400/955] 99s elapsed, ~137s remaining, 4.1 samples/s
  [450/955] 111s elapsed, ~124s remaining, 4.1 samples/s
  [500/955] 123s elapsed, ~112s remaining, 4.1 samples/s
  [550/955] 135s elapsed, ~99s remaining, 4.1 samples/s
  [600/955] 147s elapsed, ~87s remaining, 4.1 samples/s
  [650/955] 160s elapsed, ~75s remaining, 4.1 samples/s
  [700/955] 172s elapsed, ~63s remaining, 4.1 samples/s
  [750/955] 184s elapsed, ~50s remaining, 4.1 samples/s
  [800/955] 196s elapsed, ~38s remaining, 4.1 samples/s
  [850/955] 208s elapsed, ~26s remaining, 4.1 samples/s
  [900/955] 220s elapsed, ~13s remaining, 4.1 samples/s
  [950/955] 233s elapsed, ~1s remaining, 4.1 samples/s
  [955/955] 234s elapsed, ~0s remaining, 4.1 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\text_only\test
  Accuracy:           0.7183
  Weighted Precision: 0.7771
  Weighted Recall:    0.7183
  Weighted F1:        0.7263
  Macro Precision:    0.6440
  Macro Recall:       0.7395
  Macro F1:           0.6288
  Unparseable:        0

In [10]:
# 8. Humanitarian -- text_only -- train
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 5263 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_only\train.tsv
  [50/5263] 12s elapsed, ~1267s remaining, 4.1 samples/s
  [100/5263] 24s elapsed, ~1252s remaining, 4.1 samples/s
  [150/5263] 37s elapsed, ~1245s remaining, 4.1 samples/s
  [200/5263] 49s elapsed, ~1235s remaining, 4.1 samples/s
  [250/5263] 61s elapsed, ~1224s remaining, 4.1 samples/s
  [300/5263] 73s elapsed, ~1213s remaining, 4.1 samples/s
  [350/5263] 85s elapsed, ~1199s remaining, 4.1 samples/s
  [400/5263] 97s elapsed, ~1185s remaining, 4.1 samples/s
  [450/5263] 110s elapsed, ~1173s remaining, 4.1 samples/s
  [500/5263] 122s elapsed, ~1160s remaining, 4.1 samples/s
  [550/5263] 134s elapsed, ~1148s remaining, 4.1 samples/s
  [600/5263] 146s elapsed, ~1136s remaining, 4.1 samples/s
  [650/5263] 158s elapsed, ~1125s remaining, 4.1 samples/s
  [700/5263] 171s elapsed, ~1112s remaining, 4.1 samples/s
  [750/5263] 183s elapsed, ~1099s remaining, 4.1 samples/s
  [800/5263] 195s elapsed, ~1087s remaining, 4.1 samples/s
  [850/5263] 207s elapsed, ~1074s remaining, 4.1 samples/s
  [900/5263] 219s elapsed, ~1062s remaining, 4.1 samples/s
  [950/5263] 231s elapsed, ~1051s remaining, 4.1 samples/s
  [1000/5263] 244s elapsed, ~1038s remaining, 4.1 samples/s
  [1050/5263] 256s elapsed, ~1026s remaining, 4.1 samples/s
  [1100/5263] 268s elapsed, ~1013s remaining, 4.1 samples/s
  [1150/5263] 280s elapsed, ~1001s remaining, 4.1 samples/s
  [1200/5263] 292s elapsed, ~989s remaining, 4.1 samples/s
  [1250/5263] 305s elapsed, ~978s remaining, 4.1 samples/s
  [1300/5263] 317s elapsed, ~965s remaining, 4.1 samples/s
  [1350/5263] 329s elapsed, ~953s remaining, 4.1 samples/s
  [1400/5263] 341s elapsed, ~941s remaining, 4.1 samples/s
  [1450/5263] 353s elapsed, ~929s remaining, 4.1 samples/s
  [1500/5263] 365s elapsed, ~916s remaining, 4.1 samples/s
  [1550/5263] 378s elapsed, ~905s remaining, 4.1 samples/s
  [1600/5263] 390s elapsed, ~892s remaining, 4.1 samples/s
  [1650/5263] 402s elapsed, ~880s remaining, 4.1 samples/s
  [1700/5263] 414s elapsed, ~868s remaining, 4.1 samples/s
  [1750/5263] 426s elapsed, ~856s remaining, 4.1 samples/s
  [1800/5263] 438s elapsed, ~844s remaining, 4.1 samples/s
  [1850/5263] 451s elapsed, ~832s remaining, 4.1 samples/s
  [1900/5263] 463s elapsed, ~819s remaining, 4.1 samples/s
  [1950/5263] 475s elapsed, ~807s remaining, 4.1 samples/s
  [2000/5263] 487s elapsed, ~795s remaining, 4.1 samples/s
  [2050/5263] 500s elapsed, ~783s remaining, 4.1 samples/s
  [2100/5263] 512s elapsed, ~771s remaining, 4.1 samples/s
  [2150/5263] 524s elapsed, ~759s remaining, 4.1 samples/s
  [2200/5263] 536s elapsed, ~747s remaining, 4.1 samples/s
  [2250/5263] 548s elapsed, ~734s remaining, 4.1 samples/s
  [2300/5263] 561s elapsed, ~722s remaining, 4.1 samples/s
  [2350/5263] 573s elapsed, ~710s remaining, 4.1 samples/s
  [2400/5263] 585s elapsed, ~698s remaining, 4.1 samples/s
  [2450/5263] 598s elapsed, ~686s remaining, 4.1 samples/s
  [2500/5263] 610s elapsed, ~674s remaining, 4.1 samples/s
  [2550/5263] 622s elapsed, ~662s remaining, 4.1 samples/s
  [2600/5263] 634s elapsed, ~650s remaining, 4.1 samples/s
  [2650/5263] 647s elapsed, ~638s remaining, 4.1 samples/s
  [2700/5263] 659s elapsed, ~625s remaining, 4.1 samples/s
  [2750/5263] 671s elapsed, ~613s remaining, 4.1 samples/s
  [2800/5263] 683s elapsed, ~601s remaining, 4.1 samples/s
  [2850/5263] 695s elapsed, ~589s remaining, 4.1 samples/s
  [2900/5263] 708s elapsed, ~577s remaining, 4.1 samples/s
  [2950/5263] 720s elapsed, ~564s remaining, 4.1 samples/s
  [3000/5263] 732s elapsed, ~552s remaining, 4.1 samples/s
  [3050/5263] 744s elapsed, ~540s remaining, 4.1 samples/s
  [3100/5263] 757s elapsed, ~528s remaining, 4.1 samples/s
  [3150/5263] 769s elapsed, ~516s remaining, 4.1 samples/s
  [3200/5263] 781s elapsed, ~504s remaining, 4.1 samples/s
  [3250/5263] 793s elapsed, ~491s remaining, 4.1 samples/s
  [3300/5263] 805s elapsed, ~479s remaining, 4.1 samples/s
  [3350/5263] 818s elapsed, ~467s remaining, 4.1 samples/s
  [3400/5263] 830s elapsed, ~455s remaining, 4.1 samples/s
  [3450/5263] 842s elapsed, ~443s remaining, 4.1 samples/s
  [3500/5263] 855s elapsed, ~430s remaining, 4.1 samples/s
  [3550/5263] 867s elapsed, ~418s remaining, 4.1 samples/s
  [3600/5263] 879s elapsed, ~406s remaining, 4.1 samples/s
  [3650/5263] 891s elapsed, ~394s remaining, 4.1 samples/s
  [3700/5263] 904s elapsed, ~382s remaining, 4.1 samples/s
  [3750/5263] 916s elapsed, ~370s remaining, 4.1 samples/s
  [3800/5263] 929s elapsed, ~357s remaining, 4.1 samples/s
  [3850/5263] 941s elapsed, ~345s remaining, 4.1 samples/s
  [3900/5263] 953s elapsed, ~333s remaining, 4.1 samples/s
  [3950/5263] 965s elapsed, ~321s remaining, 4.1 samples/s
  [4000/5263] 978s elapsed, ~309s remaining, 4.1 samples/s
  [4050/5263] 990s elapsed, ~296s remaining, 4.1 samples/s
  [4100/5263] 1002s elapsed, ~284s remaining, 4.1 samples/s
  [4150/5263] 1014s elapsed, ~272s remaining, 4.1 samples/s
  [4200/5263] 1026s elapsed, ~260s remaining, 4.1 samples/s
  [4250/5263] 1039s elapsed, ~248s remaining, 4.1 samples/s
  [4300/5263] 1051s elapsed, ~235s remaining, 4.1 samples/s
  [4350/5263] 1063s elapsed, ~223s remaining, 4.1 samples/s
  [4400/5263] 1076s elapsed, ~211s remaining, 4.1 samples/s
  [4450/5263] 1088s elapsed, ~199s remaining, 4.1 samples/s
  [4500/5263] 1100s elapsed, ~187s remaining, 4.1 samples/s
  [4550/5263] 1113s elapsed, ~174s remaining, 4.1 samples/s
  [4600/5263] 1125s elapsed, ~162s remaining, 4.1 samples/s
  [4650/5263] 1137s elapsed, ~150s remaining, 4.1 samples/s
  [4700/5263] 1150s elapsed, ~138s remaining, 4.1 samples/s
  [4750/5263] 1162s elapsed, ~125s remaining, 4.1 samples/s
  [4800/5263] 1174s elapsed, ~113s remaining, 4.1 samples/s
  [4850/5263] 1186s elapsed, ~101s remaining, 4.1 samples/s
  [4900/5263] 1199s elapsed, ~89s remaining, 4.1 samples/s
  [4950/5263] 1211s elapsed, ~77s remaining, 4.1 samples/s
  [5000/5263] 1223s elapsed, ~64s remaining, 4.1 samples/s
  [5050/5263] 1235s elapsed, ~52s remaining, 4.1 samples/s
  [5100/5263] 1248s elapsed, ~40s remaining, 4.1 samples/s
  [5150/5263] 1260s elapsed, ~28s remaining, 4.1 samples/s
  [5200/5263] 1272s elapsed, ~15s remaining, 4.1 samples/s
  [5250/5263] 1284s elapsed, ~3s remaining, 4.1 samples/s
  [5263/5263] 1287s elapsed, ~0s remaining, 4.1 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\text_only\train
  Accuracy:           0.7245
  Weighted Precision: 0.7834
  Weighted Recall:    0.7245
  Weighted F1:        0.7325
  Macro Precision:    0.6455
  Macro Recall:       0.7511
  Macro F1:           0.6448
  Unparseable:        0

In [11]:
# 9. Humanitarian -- image_only -- test
preds, _ = run_zeroshot(
    task="humanitarian", modality="image_only", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\image_only\test.tsv
  [50/955] 23s elapsed, ~413s remaining, 2.2 samples/s
  [100/955] 47s elapsed, ~402s remaining, 2.1 samples/s
  [150/955] 70s elapsed, ~377s remaining, 2.1 samples/s
  [200/955] 97s elapsed, ~365s remaining, 2.1 samples/s
  [250/955] 121s elapsed, ~343s remaining, 2.1 samples/s
  [300/955] 147s elapsed, ~322s remaining, 2.0 samples/s
  [350/955] 174s elapsed, ~301s remaining, 2.0 samples/s
  [400/955] 200s elapsed, ~277s remaining, 2.0 samples/s
  [450/955] 227s elapsed, ~255s remaining, 2.0 samples/s
  [500/955] 252s elapsed, ~229s remaining, 2.0 samples/s
  [550/955] 277s elapsed, ~204s remaining, 2.0 samples/s
  [600/955] 304s elapsed, ~180s remaining, 2.0 samples/s
  [650/955] 329s elapsed, ~155s remaining, 2.0 samples/s
  [700/955] 355s elapsed, ~130s remaining, 2.0 samples/s
  [750/955] 382s elapsed, ~104s remaining, 2.0 samples/s
  [800/955] 409s elapsed, ~79s remaining, 2.0 samples/s
  [850/955] 435s elapsed, ~54s remaining, 2.0 samples/s
  [900/955] 460s elapsed, ~28s remaining, 2.0 samples/s
  [950/955] 486s elapsed, ~3s remaining, 2.0 samples/s
  [955/955] 488s elapsed, ~0s remaining, 2.0 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\image_only\test
  Accuracy:           0.8147
  Weighted Precision: 0.8208
  Weighted Recall:    0.8147
  Weighted F1:        0.8150
  Macro Precision:    0.7388
  Macro Recall:       0.7297
  Macro F1:           0.7283
  Unparseable:        0

In [12]:
# 10. Humanitarian -- image_only -- train
preds, _ = run_zeroshot(
    task="humanitarian", modality="image_only", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 6126 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\image_only\train.tsv
  [50/6126] 29s elapsed, ~3502s remaining, 1.7 samples/s
  [100/6126] 57s elapsed, ~3450s remaining, 1.7 samples/s
  [150/6126] 87s elapsed, ~3460s remaining, 1.7 samples/s
  [200/6126] 111s elapsed, ~3302s remaining, 1.8 samples/s
  [250/6126] 141s elapsed, ~3307s remaining, 1.8 samples/s
  [300/6126] 170s elapsed, ~3293s remaining, 1.8 samples/s
  [350/6126] 199s elapsed, ~3283s remaining, 1.8 samples/s
  [400/6126] 226s elapsed, ~3229s remaining, 1.8 samples/s
  [450/6126] 255s elapsed, ~3218s remaining, 1.8 samples/s
  [500/6126] 284s elapsed, ~3198s remaining, 1.8 samples/s
  [550/6126] 315s elapsed, ~3192s remaining, 1.7 samples/s
  [600/6126] 346s elapsed, ~3189s remaining, 1.7 samples/s
  [650/6126] 378s elapsed, ~3189s remaining, 1.7 samples/s
  [700/6126] 411s elapsed, ~3183s remaining, 1.7 samples/s
  [750/6126] 442s elapsed, ~3169s remaining, 1.7 samples/s
  [800/6126] 471s elapsed, ~3134s remaining, 1.7 samples/s
  [850/6126] 499s elapsed, ~3100s remaining, 1.7 samples/s
  [900/6126] 529s elapsed, ~3072s remaining, 1.7 samples/s
  [950/6126] 559s elapsed, ~3045s remaining, 1.7 samples/s
  [1000/6126] 588s elapsed, ~3015s remaining, 1.7 samples/s
  [1050/6126] 618s elapsed, ~2987s remaining, 1.7 samples/s
  [1100/6126] 649s elapsed, ~2965s remaining, 1.7 samples/s
  [1150/6126] 680s elapsed, ~2944s remaining, 1.7 samples/s
  [1200/6126] 712s elapsed, ~2923s remaining, 1.7 samples/s
  [1250/6126] 739s elapsed, ~2885s remaining, 1.7 samples/s
  [1300/6126] 768s elapsed, ~2852s remaining, 1.7 samples/s
  [1350/6126] 798s elapsed, ~2824s remaining, 1.7 samples/s
  [1400/6126] 831s elapsed, ~2805s remaining, 1.7 samples/s
  [1450/6126] 862s elapsed, ~2780s remaining, 1.7 samples/s
  [1500/6126] 891s elapsed, ~2749s remaining, 1.7 samples/s
  [1550/6126] 925s elapsed, ~2731s remaining, 1.7 samples/s
  [1600/6126] 955s elapsed, ~2702s remaining, 1.7 samples/s
  [1650/6126] 982s elapsed, ~2665s remaining, 1.7 samples/s
  [1700/6126] 1007s elapsed, ~2622s remaining, 1.7 samples/s
  [1750/6126] 1033s elapsed, ~2582s remaining, 1.7 samples/s
  [1800/6126] 1059s elapsed, ~2545s remaining, 1.7 samples/s
  [1850/6126] 1086s elapsed, ~2509s remaining, 1.7 samples/s
  [1900/6126] 1112s elapsed, ~2472s remaining, 1.7 samples/s
  [1950/6126] 1136s elapsed, ~2432s remaining, 1.7 samples/s
  [2000/6126] 1161s elapsed, ~2395s remaining, 1.7 samples/s
  [2050/6126] 1186s elapsed, ~2359s remaining, 1.7 samples/s
  [2100/6126] 1211s elapsed, ~2323s remaining, 1.7 samples/s
  [2150/6126] 1238s elapsed, ~2289s remaining, 1.7 samples/s
  [2200/6126] 1263s elapsed, ~2254s remaining, 1.7 samples/s
  [2250/6126] 1287s elapsed, ~2217s remaining, 1.7 samples/s
  [2300/6126] 1313s elapsed, ~2184s remaining, 1.8 samples/s
  [2350/6126] 1337s elapsed, ~2149s remaining, 1.8 samples/s
  [2400/6126] 1363s elapsed, ~2115s remaining, 1.8 samples/s
  [2450/6126] 1390s elapsed, ~2085s remaining, 1.8 samples/s
  [2500/6126] 1414s elapsed, ~2051s remaining, 1.8 samples/s
  [2550/6126] 1439s elapsed, ~2018s remaining, 1.8 samples/s
  [2600/6126] 1465s elapsed, ~1987s remaining, 1.8 samples/s
  [2650/6126] 1490s elapsed, ~1955s remaining, 1.8 samples/s
  [2700/6126] 1515s elapsed, ~1922s remaining, 1.8 samples/s
  [2750/6126] 1541s elapsed, ~1892s remaining, 1.8 samples/s
  [2800/6126] 1566s elapsed, ~1861s remaining, 1.8 samples/s
  [2850/6126] 1593s elapsed, ~1831s remaining, 1.8 samples/s
  [2900/6126] 1618s elapsed, ~1800s remaining, 1.8 samples/s
  [2950/6126] 1644s elapsed, ~1770s remaining, 1.8 samples/s
  [3000/6126] 1670s elapsed, ~1740s remaining, 1.8 samples/s
  [3050/6126] 1695s elapsed, ~1710s remaining, 1.8 samples/s
  [3100/6126] 1722s elapsed, ~1681s remaining, 1.8 samples/s
  [3150/6126] 1749s elapsed, ~1652s remaining, 1.8 samples/s
  [3200/6126] 1775s elapsed, ~1623s remaining, 1.8 samples/s
  [3250/6126] 1799s elapsed, ~1592s remaining, 1.8 samples/s
  [3300/6126] 1826s elapsed, ~1564s remaining, 1.8 samples/s
  [3350/6126] 1850s elapsed, ~1533s remaining, 1.8 samples/s
  [3400/6126] 1875s elapsed, ~1504s remaining, 1.8 samples/s
  [3450/6126] 1901s elapsed, ~1475s remaining, 1.8 samples/s
  [3500/6126] 1924s elapsed, ~1444s remaining, 1.8 samples/s
  [3550/6126] 1952s elapsed, ~1416s remaining, 1.8 samples/s
  [3600/6126] 1975s elapsed, ~1386s remaining, 1.8 samples/s
  [3650/6126] 1999s elapsed, ~1356s remaining, 1.8 samples/s
  [3700/6126] 2025s elapsed, ~1328s remaining, 1.8 samples/s
  [3750/6126] 2052s elapsed, ~1300s remaining, 1.8 samples/s
  [3800/6126] 2078s elapsed, ~1272s remaining, 1.8 samples/s
  [3850/6126] 2106s elapsed, ~1245s remaining, 1.8 samples/s
  [3900/6126] 2131s elapsed, ~1216s remaining, 1.8 samples/s
  [3950/6126] 2155s elapsed, ~1187s remaining, 1.8 samples/s
  [4000/6126] 2182s elapsed, ~1160s remaining, 1.8 samples/s
  [4050/6126] 2207s elapsed, ~1131s remaining, 1.8 samples/s
  [4100/6126] 2234s elapsed, ~1104s remaining, 1.8 samples/s
  [4150/6126] 2260s elapsed, ~1076s remaining, 1.8 samples/s
  [4200/6126] 2286s elapsed, ~1048s remaining, 1.8 samples/s
  [4250/6126] 2312s elapsed, ~1020s remaining, 1.8 samples/s
  [4300/6126] 2337s elapsed, ~992s remaining, 1.8 samples/s
  [4350/6126] 2362s elapsed, ~965s remaining, 1.8 samples/s
  [4400/6126] 2390s elapsed, ~938s remaining, 1.8 samples/s
  [4450/6126] 2414s elapsed, ~909s remaining, 1.8 samples/s
  [4500/6126] 2441s elapsed, ~882s remaining, 1.8 samples/s
  [4550/6126] 2467s elapsed, ~855s remaining, 1.8 samples/s
  [4600/6126] 2491s elapsed, ~826s remaining, 1.8 samples/s
  [4650/6126] 2517s elapsed, ~799s remaining, 1.8 samples/s
  [4700/6126] 2543s elapsed, ~771s remaining, 1.8 samples/s
  [4750/6126] 2566s elapsed, ~743s remaining, 1.9 samples/s
  [4800/6126] 2593s elapsed, ~716s remaining, 1.9 samples/s
  [4850/6126] 2618s elapsed, ~689s remaining, 1.9 samples/s
  [4900/6126] 2644s elapsed, ~661s remaining, 1.9 samples/s
  [4950/6126] 2669s elapsed, ~634s remaining, 1.9 samples/s
  [5000/6126] 2695s elapsed, ~607s remaining, 1.9 samples/s
  [5050/6126] 2720s elapsed, ~580s remaining, 1.9 samples/s
  [5100/6126] 2745s elapsed, ~552s remaining, 1.9 samples/s
  [5150/6126] 2769s elapsed, ~525s remaining, 1.9 samples/s
  [5200/6126] 2794s elapsed, ~498s remaining, 1.9 samples/s
  [5250/6126] 2820s elapsed, ~471s remaining, 1.9 samples/s
  [5300/6126] 2846s elapsed, ~444s remaining, 1.9 samples/s
  [5350/6126] 2871s elapsed, ~416s remaining, 1.9 samples/s
  [5400/6126] 2897s elapsed, ~389s remaining, 1.9 samples/s
  [5450/6126] 2922s elapsed, ~362s remaining, 1.9 samples/s
  [5500/6126] 2945s elapsed, ~335s remaining, 1.9 samples/s
  [5550/6126] 2970s elapsed, ~308s remaining, 1.9 samples/s
  [5600/6126] 2997s elapsed, ~281s remaining, 1.9 samples/s
  [5650/6126] 3023s elapsed, ~255s remaining, 1.9 samples/s
  [5700/6126] 3049s elapsed, ~228s remaining, 1.9 samples/s
  [5750/6126] 3074s elapsed, ~201s remaining, 1.9 samples/s
  [5800/6126] 3100s elapsed, ~174s remaining, 1.9 samples/s
  [5850/6126] 3125s elapsed, ~147s remaining, 1.9 samples/s
  [5900/6126] 3151s elapsed, ~121s remaining, 1.9 samples/s
  [5950/6126] 3178s elapsed, ~94s remaining, 1.9 samples/s
  [6000/6126] 3204s elapsed, ~67s remaining, 1.9 samples/s
  [6050/6126] 3228s elapsed, ~41s remaining, 1.9 samples/s
  [6100/6126] 3253s elapsed, ~14s remaining, 1.9 samples/s
  [6126/6126] 3268s elapsed, ~0s remaining, 1.9 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\image_only\train
  Accuracy:           0.8177
  Weighted Precision: 0.8305
  Weighted Recall:    0.8177
  Weighted F1:        0.8199
  Macro Precision:    0.7617
  Macro Recall:       0.7697
  Macro F1:           0.7590
  Unparseable:        0

In [13]:
# 11. Humanitarian -- text_image -- test
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_image", split="test",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 955 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_image\test.tsv
  [50/955] 25s elapsed, ~457s remaining, 2.0 samples/s
  [100/955] 51s elapsed, ~434s remaining, 2.0 samples/s
  [150/955] 76s elapsed, ~408s remaining, 2.0 samples/s
  [200/955] 105s elapsed, ~396s remaining, 1.9 samples/s
  [250/955] 132s elapsed, ~372s remaining, 1.9 samples/s
  [300/955] 160s elapsed, ~350s remaining, 1.9 samples/s
  [350/955] 189s elapsed, ~327s remaining, 1.9 samples/s
  [400/955] 217s elapsed, ~300s remaining, 1.8 samples/s
  [450/955] 247s elapsed, ~277s remaining, 1.8 samples/s
  [500/955] 274s elapsed, ~249s remaining, 1.8 samples/s
  [550/955] 302s elapsed, ~222s remaining, 1.8 samples/s
  [600/955] 331s elapsed, ~196s remaining, 1.8 samples/s
  [650/955] 358s elapsed, ~168s remaining, 1.8 samples/s
  [700/955] 386s elapsed, ~140s remaining, 1.8 samples/s
  [750/955] 414s elapsed, ~113s remaining, 1.8 samples/s
  [800/955] 444s elapsed, ~86s remaining, 1.8 samples/s
  [850/955] 472s elapsed, ~58s remaining, 1.8 samples/s
  [900/955] 499s elapsed, ~31s remaining, 1.8 samples/s
  [950/955] 528s elapsed, ~3s remaining, 1.8 samples/s
  [955/955] 530s elapsed, ~0s remaining, 1.8 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\text_image\test
  Accuracy:           0.7372
  Weighted Precision: 0.8153
  Weighted Recall:    0.7372
  Weighted F1:        0.7474
  Macro Precision:    0.6886
  Macro Recall:       0.7460
  Macro F1:           0.6639
  Unparseable:        0

In [14]:
# 12. Humanitarian -- text_image -- train
preds, _ = run_zeroshot(
    task="humanitarian", modality="text_image", split="train",
    model_id=MODEL_ID, data_root=DATA_ROOT, output_dir=OUTPUT_DIR,
    model=model, processor=processor,
)
cleanup(preds)

Loaded 6126 samples from D:\Workspace\Cotrain_CrisisMMD\data\CrisisMMD\tasks\humanitarian\text_image\train.tsv
  [50/6126] 32s elapsed, ~3836s remaining, 1.6 samples/s
  [100/6126] 62s elapsed, ~3763s remaining, 1.6 samples/s
  [150/6126] 95s elapsed, ~3776s remaining, 1.6 samples/s
  [200/6126] 122s elapsed, ~3622s remaining, 1.6 samples/s
  [250/6126] 154s elapsed, ~3617s remaining, 1.6 samples/s
  [300/6126] 185s elapsed, ~3599s remaining, 1.6 samples/s
  [350/6126] 218s elapsed, ~3591s remaining, 1.6 samples/s
  [400/6126] 246s elapsed, ~3523s remaining, 1.6 samples/s
  [450/6126] 278s elapsed, ~3505s remaining, 1.6 samples/s
  [500/6126] 309s elapsed, ~3481s remaining, 1.6 samples/s
  [550/6126] 342s elapsed, ~3465s remaining, 1.6 samples/s
  [600/6126] 375s elapsed, ~3455s remaining, 1.6 samples/s
  [650/6126] 409s elapsed, ~3450s remaining, 1.6 samples/s
  [700/6126] 444s elapsed, ~3442s remaining, 1.6 samples/s
  [750/6126] 477s elapsed, ~3420s remaining, 1.6 samples/s
  [800/6126] 508s elapsed, ~3379s remaining, 1.6 samples/s
  [850/6126] 538s elapsed, ~3341s remaining, 1.6 samples/s
  [900/6126] 570s elapsed, ~3310s remaining, 1.6 samples/s
  [950/6126] 602s elapsed, ~3282s remaining, 1.6 samples/s
  [1000/6126] 635s elapsed, ~3253s remaining, 1.6 samples/s
  [1050/6126] 666s elapsed, ~3221s remaining, 1.6 samples/s
  [1100/6126] 700s elapsed, ~3199s remaining, 1.6 samples/s
  [1150/6126] 733s elapsed, ~3172s remaining, 1.6 samples/s
  [1200/6126] 766s elapsed, ~3146s remaining, 1.6 samples/s
  [1250/6126] 796s elapsed, ~3105s remaining, 1.6 samples/s
  [1300/6126] 826s elapsed, ~3067s remaining, 1.6 samples/s
  [1350/6126] 858s elapsed, ~3036s remaining, 1.6 samples/s
  [1400/6126] 893s elapsed, ~3014s remaining, 1.6 samples/s
  [1450/6126] 926s elapsed, ~2986s remaining, 1.6 samples/s
  [1500/6126] 957s elapsed, ~2952s remaining, 1.6 samples/s
  [1550/6126] 994s elapsed, ~2933s remaining, 1.6 samples/s
  [1600/6126] 1026s elapsed, ~2902s remaining, 1.6 samples/s
  [1650/6126] 1056s elapsed, ~2864s remaining, 1.6 samples/s
  [1700/6126] 1082s elapsed, ~2818s remaining, 1.6 samples/s
  [1750/6126] 1110s elapsed, ~2775s remaining, 1.6 samples/s
  [1800/6126] 1138s elapsed, ~2735s remaining, 1.6 samples/s
  [1850/6126] 1167s elapsed, ~2698s remaining, 1.6 samples/s
  [1900/6126] 1196s elapsed, ~2660s remaining, 1.6 samples/s
  [1950/6126] 1222s elapsed, ~2617s remaining, 1.6 samples/s
  [2000/6126] 1250s elapsed, ~2578s remaining, 1.6 samples/s
  [2050/6126] 1277s elapsed, ~2540s remaining, 1.6 samples/s
  [2100/6126] 1305s elapsed, ~2501s remaining, 1.6 samples/s
  [2150/6126] 1333s elapsed, ~2466s remaining, 1.6 samples/s
  [2200/6126] 1360s elapsed, ~2428s remaining, 1.6 samples/s
  [2250/6126] 1386s elapsed, ~2388s remaining, 1.6 samples/s
  [2300/6126] 1414s elapsed, ~2353s remaining, 1.6 samples/s
  [2350/6126] 1441s elapsed, ~2315s remaining, 1.6 samples/s
  [2400/6126] 1468s elapsed, ~2279s remaining, 1.6 samples/s
  [2450/6126] 1498s elapsed, ~2247s remaining, 1.6 samples/s
  [2500/6126] 1524s elapsed, ~2210s remaining, 1.6 samples/s
  [2550/6126] 1551s elapsed, ~2175s remaining, 1.6 samples/s
  [2600/6126] 1579s elapsed, ~2142s remaining, 1.6 samples/s
  [2650/6126] 1606s elapsed, ~2107s remaining, 1.6 samples/s
  [2700/6126] 1633s elapsed, ~2072s remaining, 1.7 samples/s
  [2750/6126] 1661s elapsed, ~2039s remaining, 1.7 samples/s
  [2800/6126] 1689s elapsed, ~2006s remaining, 1.7 samples/s
  [2850/6126] 1717s elapsed, ~1973s remaining, 1.7 samples/s
  [2900/6126] 1744s elapsed, ~1940s remaining, 1.7 samples/s
  [2950/6126] 1773s elapsed, ~1908s remaining, 1.7 samples/s
  [3000/6126] 1800s elapsed, ~1876s remaining, 1.7 samples/s
  [3050/6126] 1828s elapsed, ~1844s remaining, 1.7 samples/s
  [3100/6126] 1857s elapsed, ~1813s remaining, 1.7 samples/s
  [3150/6126] 1887s elapsed, ~1782s remaining, 1.7 samples/s
  [3200/6126] 1914s elapsed, ~1750s remaining, 1.7 samples/s
  [3250/6126] 1941s elapsed, ~1717s remaining, 1.7 samples/s
  [3300/6126] 1970s elapsed, ~1687s remaining, 1.7 samples/s
  [3350/6126] 1995s elapsed, ~1653s remaining, 1.7 samples/s
  [3400/6126] 2023s elapsed, ~1622s remaining, 1.7 samples/s
  [3450/6126] 2051s elapsed, ~1591s remaining, 1.7 samples/s
  [3500/6126] 2076s elapsed, ~1558s remaining, 1.7 samples/s
  [3550/6126] 2106s elapsed, ~1528s remaining, 1.7 samples/s
  [3600/6126] 2132s elapsed, ~1496s remaining, 1.7 samples/s
  [3650/6126] 2158s elapsed, ~1464s remaining, 1.7 samples/s
  [3700/6126] 2186s elapsed, ~1433s remaining, 1.7 samples/s
  [3750/6126] 2215s elapsed, ~1403s remaining, 1.7 samples/s
  [3800/6126] 2243s elapsed, ~1373s remaining, 1.7 samples/s
  [3850/6126] 2273s elapsed, ~1344s remaining, 1.7 samples/s
  [3900/6126] 2300s elapsed, ~1313s remaining, 1.7 samples/s
  [3950/6126] 2327s elapsed, ~1282s remaining, 1.7 samples/s
  [4000/6126] 2356s elapsed, ~1252s remaining, 1.7 samples/s
  [4050/6126] 2383s elapsed, ~1221s remaining, 1.7 samples/s
  [4100/6126] 2412s elapsed, ~1192s remaining, 1.7 samples/s
  [4150/6126] 2440s elapsed, ~1162s remaining, 1.7 samples/s
  [4200/6126] 2470s elapsed, ~1133s remaining, 1.7 samples/s
  [4250/6126] 2499s elapsed, ~1103s remaining, 1.7 samples/s
  [4300/6126] 2527s elapsed, ~1073s remaining, 1.7 samples/s
  [4350/6126] 2555s elapsed, ~1043s remaining, 1.7 samples/s
  [4400/6126] 2585s elapsed, ~1014s remaining, 1.7 samples/s
  [4450/6126] 2611s elapsed, ~983s remaining, 1.7 samples/s
  [4500/6126] 2640s elapsed, ~954s remaining, 1.7 samples/s
  [4550/6126] 2668s elapsed, ~924s remaining, 1.7 samples/s
  [4600/6126] 2694s elapsed, ~894s remaining, 1.7 samples/s
  [4650/6126] 2723s elapsed, ~864s remaining, 1.7 samples/s
  [4700/6126] 2750s elapsed, ~834s remaining, 1.7 samples/s
  [4750/6126] 2775s elapsed, ~804s remaining, 1.7 samples/s
  [4800/6126] 2805s elapsed, ~775s remaining, 1.7 samples/s
  [4850/6126] 2833s elapsed, ~745s remaining, 1.7 samples/s
  [4900/6126] 2861s elapsed, ~716s remaining, 1.7 samples/s
  [4950/6126] 2889s elapsed, ~686s remaining, 1.7 samples/s
  [5000/6126] 2917s elapsed, ~657s remaining, 1.7 samples/s
  [5050/6126] 2944s elapsed, ~627s remaining, 1.7 samples/s
  [5100/6126] 2971s elapsed, ~598s remaining, 1.7 samples/s
  [5150/6126] 2997s elapsed, ~568s remaining, 1.7 samples/s
  [5200/6126] 3025s elapsed, ~539s remaining, 1.7 samples/s
  [5250/6126] 3053s elapsed, ~509s remaining, 1.7 samples/s
  [5300/6126] 3081s elapsed, ~480s remaining, 1.7 samples/s
  [5350/6126] 3108s elapsed, ~451s remaining, 1.7 samples/s
  [5400/6126] 3136s elapsed, ~422s remaining, 1.7 samples/s
  [5450/6126] 3164s elapsed, ~392s remaining, 1.7 samples/s
  [5500/6126] 3189s elapsed, ~363s remaining, 1.7 samples/s
  [5550/6126] 3217s elapsed, ~334s remaining, 1.7 samples/s
  [5600/6126] 3246s elapsed, ~305s remaining, 1.7 samples/s
  [5650/6126] 3275s elapsed, ~276s remaining, 1.7 samples/s
  [5700/6126] 3303s elapsed, ~247s remaining, 1.7 samples/s
  [5750/6126] 3330s elapsed, ~218s remaining, 1.7 samples/s
  [5800/6126] 3358s elapsed, ~189s remaining, 1.7 samples/s
  [5850/6126] 3386s elapsed, ~160s remaining, 1.7 samples/s
  [5900/6126] 3413s elapsed, ~131s remaining, 1.7 samples/s
  [5950/6126] 3441s elapsed, ~102s remaining, 1.7 samples/s
  [6000/6126] 3470s elapsed, ~73s remaining, 1.7 samples/s
  [6050/6126] 3496s elapsed, ~44s remaining, 1.7 samples/s
  [6100/6126] 3523s elapsed, ~15s remaining, 1.7 samples/s
  [6126/6126] 3538s elapsed, ~0s remaining, 1.7 samples/s

Results saved to D:\Workspace\Cotrain_CrisisMMD\results\zeroshot\qwen3-vl-8b\humanitarian\text_image\train
  Accuracy:           0.7416
  Weighted Precision: 0.8307
  Weighted Recall:    0.7416
  Weighted F1:        0.7544
  Macro Precision:    0.7062
  Macro Recall:       0.7623
  Macro F1:           0.6842
  Unparseable:        0

### Humanitarian Summary

In [15]:
show_summary("humanitarian")

Task: humanitarian
Model: qwen3-vl-8b

     Modality  Split  Samples Accuracy Weighted F1 Macro F1  Unparseable
0   text_only   test      955   0.7183      0.7263   0.6288            0
1   text_only  train     5263   0.7245      0.7325   0.6448            0
2  image_only   test      955   0.8147      0.8150   0.7283            0
3  image_only  train     6126   0.8177      0.8199   0.7590            0
4  text_image   test      955   0.7372      0.7474   0.6639            0
5  text_image  train     6126   0.7416      0.7544   0.6842            0

## Cleanup -- Free GPU Memory

In [16]:
del model, processor

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    print(f"GPU memory allocated: {torch.cuda.memory_allocated()/1e9:.1f} GB")
    print(f"GPU memory reserved:  {torch.cuda.memory_reserved()/1e9:.1f} GB")

print("\nAll 12 experiments complete.")
print("Next step: generate pseudo-labels with:")
print("  python scripts/create_pseudo_labels.py --model qwen3-vl-8b")

GPU memory allocated: 0.0 GB
GPU memory reserved:  0.0 GB

All 12 experiments complete.
Next step: generate pseudo-labels with:
  python scripts/create_pseudo_labels.py --model qwen3-vl-8b